const fs = require('fs');
const path = require('path');

const words = [];

// Helper
const addWords = (category, difficulty, arr) => {
  arr.forEach(([it, cz, pron, exIt, exCz]) => {
    words.push({
      italian: it,
      czech: cz,
      category,
      difficulty,
      pronunciation: pron || it,
      example_it: exIt || `Questo è ${it}.`,
      example_cz: exCz || `Toto je ${cz}.`
    });
  });
};

// 1. Tělo a zdraví
const telo = [
  ["la testa", "hlava", "la tésta", "Mi fa male la testa.", "Bolí mě hlava."],
  ["il braccio", "paže", "il bráčo", "Ho rotto il braccio.", "Zlomil jsem si paži."],
  ["la mano", "ruka", "la máno", "Dammi la mano.", "Dej mi ruku."],
  ["la gamba", "noha (celá)", "la gámba", "La gamba è lunga.", "Noha je dlouhá."],
  ["il piede", "noha (chodidlo)", "il pjéde", "Mi fa male il piede.", "Bolí mě noha."],
  ["il dito", "prst", "il díto", "Ho tagliato il dito.", "Řízl jsem se do prstu."],
  ["l'occhio", "oko", "lókjo", "L'occhio è blu.", "Oko je modré."],
  ["l'orecchio", "ucho", "lorékjo", "Mi fa male l'orecchio.", "Bolí mě ucho."],
  ["il naso", "nos", "il názo", "Ho il naso chiuso.", "Mám ucpaný nos."],
  ["la bocca", "ústa", "la bóka", "Apri la bocca.", "Otevři ústa."],
  ["il dente", "zub", "il dénte", "Devo andare dal dentista per un dente.", "Musím k zubaři kvůli zubu."],
  ["il capello", "vlas", "il kapélo", "I capelli sono neri.", "Vlasy jsou černé."],
  ["il collo", "krk", "il kólo", "Il collo è lungo.", "Krk je dlouhý."],
  ["la spalla", "rameno", "la spála", "Mi fa male la spalla.", "Bolí mě rameno."],
  ["il petto", "hruď", "il péto", "Respiro con il petto.", "Dýchám hrudí."],
  ["la pancia", "břicho", "la pánča", "Ho mal di pancia.", "Bolí mě břicho."],
  ["la schiena", "záda", "la skjéna", "Mi fa male la schiena.", "Bolí mě záda."],
  ["il cuore", "srdce", "il kuóre", "Il cuore batte.", "Srdce bije."],
  ["il sangue", "krev", "il sángue", "Il sangue è rosso.", "Krev je červená."],
  ["il muscolo", "sval", "il múskolo", "Il muscolo è forte.", "Sval je silný."],
  ["l'osso", "kost", "lóso", "Il cane morde l'osso.", "Pes kouše kost."],
  ["il medico", "lékař", "il médiko", "Vado dal medico.", "Jdu k lékaři."],
  ["l'infermiere", "zdravotní bratr", "linfermjére", "L'infermiere mi aiuta.", "Zdravotní bratr mi pomáhá."],
  ["la medicina", "lék", "la medičína", "Prendo la medicina.", "Beru lék."],
  ["la pillola", "pilulka", "la pílola", "Prendi questa pillola.", "Vezmi si tuto pilulku."],
  ["l'ospedale", "nemocnice", "lospedále", "L'ospedale è grande.", "Nemocnice je velká."],
  ["la febbre", "horečka", "la fébre", "Ho la febbre alta.", "Mám vysokou horečku."],
  ["la tosse", "kašel", "la tóse", "Ho una brutta tosse.", "Mám ošklivý kašel."],
  ["il raffreddore", "rýma", "il rafredóre", "Ho il raffreddore.", "Mám rýmu."],
  ["il dolore", "bolest", "il dolóre", "Sento molto dolore.", "Cítím velkou bolest."],
  ["la ferita", "zranění, rána", "la feríta", "La ferita sanguina.", "Rána krvácí."],
  ["il cerotto", "náplast", "il čeróto", "Metti un cerotto.", "Dej si náplast."],
  ["sano", "zdravý", "sáno", "Mangio cibo sano.", "Jím zdravé jídlo."],
  ["malato", "nemocný", "maláto", "Oggi sono malato.", "Dnes jsem nemocný."],
  ["stanco", "unavený", "stánko", "Sono molto stanco.", "Jsem velmi unavený."],
  ["il ginocchio", "koleno", "il džinókjo", "Mi fa male il ginocchio.", "Bolí mě koleno."],
  ["il gomito", "loket", "il gómito", "Ho battuto il gomito.", "Uhodil jsem se do lokte."],
  ["la caviglia", "kotník", "la kavílja", "Ho storto la caviglia.", "Vyvrtl jsem si kotník."],
  ["la faccia", "obličej", "la fáča", "Lavo la faccia.", "Myju si obličej."],
  ["la pelle", "kůže", "la péle", "La pelle è morbida.", "Kůže je jemná."]
];

// 2. Dům a domácnost
const dum = [
  ["la casa", "dům", "la káza", "La casa è bella.", "Dům je hezký."],
  ["l'appartamento", "byt", "lapartaménto", "Vivo in un appartamento.", "Bydlím v bytě."],
  ["la stanza", "pokoj", "la stánca", "La stanza è grande.", "Pokoj je velký."],
  ["la camera da letto", "ložnice", "la kámera da léto", "Dormo nella camera da letto.", "Spím v ložnici."],
  ["il soggiorno", "obývací pokoj", "il sodžórno", "Guardo la TV nel soggiorno.", "Dívám se na TV v obýváku."],
  ["la cucina", "kuchyně", "la kučína", "Cucino in cucina.", "Vařím v kuchyni."],
  ["il bagno", "koupelna", "il báňo", "Faccio la doccia nel bagno.", "Sprchuji se v koupelně."],
  ["il corridoio", "chodba", "il koridójo", "Il corridoio è lungo.", "Chodba je dlouhá."],
  ["il balcone", "balkon", "il balkóne", "Bevo il caffè sul balcone.", "Piji kávu na balkóně."],
  ["il giardino", "zahrada", "il džardíno", "Il giardino ha molti fiori.", "Zahrada má mnoho květin."],
  ["il tetto", "střecha", "il této", "Il gatto è sul tetto.", "Kočka je na střeše."],
  ["il muro", "zeď", "il múro", "Il muro è bianco.", "Zeď je bílá."],
  ["la porta", "dveře", "la pórta", "Apri la porta.", "Otevři dveře."],
  ["la finestra", "okno", "la finéstra", "Chiudi la finestra.", "Zavři okno."],
  ["il pavimento", "podlaha", "il paviménto", "Pulisco il pavimento.", "Uklízím podlahu."],
  ["il soffitto", "strop", "il sofíto", "Il soffitto è alto.", "Strop je vysoký."],
  ["le scale", "schody", "le skále", "Salgo le scale.", "Jdu po schodech nahoru."],
  ["l'ascensore", "výtah", "lašensóre", "Prendo l'ascensore.", "Jedu výtahem."],
  ["il tavolo", "stůl", "il távolo", "Il libro è sul tavolo.", "Kniha je na stole."],
  ["la sedia", "židle", "la sédja", "Mi siedo sulla sedia.", "Sedám si na židli."],
  ["il letto", "postel", "il léto", "Il letto è comodo.", "Postel je pohodlná."],
  ["l'armadio", "skříň", "larmádjo", "Metto i vestiti nell'armadio.", "Dávám oblečení do skříně."],
  ["il divano", "pohovka", "il diváno", "Riposo sul divano.", "Odpočívám na pohovce."],
  ["la poltrona", "křeslo", "la poltróna", "Il nonno è sulla poltrona.", "Dědeček je v křesle."],
  ["il tappeto", "koberec", "il tapéto", "Il tappeto è rosso.", "Koberec je červený."],
  ["lo specchio", "zrcadlo", "lo spékjo", "Mi guardo nello specchio.", "Dívám se do zrcadla."],
  ["il lampadario", "lustr", "il lampadárjo", "Il lampadario fa luce.", "Lustr svítí."],
  ["la lampada", "lampa", "la lámpada", "Accendi la lampada.", "Rozsviť lampu."],
  ["il quadro", "obraz", "il kuádro", "Il quadro è bello.", "Obraz je hezký."],
  ["l'orologio", "hodiny", "lorolódžo", "L'orologio segna le tre.", "Hodiny ukazují tři."],
  ["la televisione", "televize", "la televijóne", "Guardo la televisione.", "Dívám se na televizi."],
  ["il frigorifero", "lednička", "il frigorífero", "Il latte è nel frigorifero.", "Mléko je v lednici."],
  ["il forno", "trouba", "il fórno", "Cuocio la pizza nel forno.", "Peču pizzu v troubě."],
  ["la lavatrice", "pračka", "la lavatríče", "La lavatrice lava i vestiti.", "Pračka pere oblečení."],
  ["il piatto", "talíř", "il pjáto", "Il piatto è pulito.", "Talíř je čistý."],
  ["il bicchiere", "sklenice", "il bikjére", "Bevo un bicchiere d'acqua.", "Piji sklenici vody."],
  ["la tazza", "šálek", "la táca", "Bevo una tazza di tè.", "Piji šálek čaje."],
  ["la pentola", "hrnec", "la péntola", "La pentola è sul fuoco.", "Hrnec je na ohni."],
  ["la padella", "pánev", "la padéla", "Faccio l'uovo in padella.", "Dělám vejce na pánvi."],
  ["il coltello", "nůž", "il koltélo", "Taglio con il coltello.", "Krájím nožem."],
  ["la forchetta", "vidlička", "la forkéta", "Mangio con la forchetta.", "Jím vidličkou."],
  ["il cucchiaio", "lžíce", "il kukiájo", "Prendo la zuppa con il cucchiaio.", "Beru polévku lžící."],
  ["il tovagliolo", "ubrousek", "il tovaljólo", "Uso il tovagliolo.", "Používám ubrousek."]
];

// 3. Volný čas a sport
const sport = [
  ["il calcio", "fotbal", "il kálčo", "Gioco a calcio.", "Hraju fotbal."],
  ["il tennis", "tenis", "il ténis", "Il tennis è divertente.", "Tenis je zábavný."],
  ["la pallavolo", "volejbal", "la palavólo", "Giochiamo a pallavolo.", "Hrajeme volejbal."],
  ["il basket", "basketbal", "il básket", "Tiro la palla a basket.", "Házím míč na basketbal."],
  ["il nuoto", "plavání", "il nuóto", "Il nuoto fa bene.", "Plavání je zdravé."],
  ["la corsa", "běh", "la kórsa", "Faccio una corsa.", "Jdu si zaběhat."],
  ["la bicicletta", "kolo", "la bičikléta", "Vado in bicicletta.", "Jedu na kole."],
  ["lo sci", "lyžování", "lo ši", "Mi piace lo sci.", "Mám rád lyžování."],
  ["lo snowboard", "snowboard", "lo snóubord", "Vado sullo snowboard.", "Jezdím na snowboardu."],
  ["la palestra", "posilovna", "la paléstra", "Mi alleno in palestra.", "Trénuji v posilovně."],
  ["l'allenamento", "trénink", "lalenaménto", "L'allenamento è duro.", "Trénink je těžký."],
  ["la partita", "zápas", "la partíta", "Guardo la partita in TV.", "Dívám se na zápas v TV."],
  ["il giocatore", "hráč", "il džokatóre", "Il giocatore corre veloce.", "Hráč běží rychle."],
  ["la squadra", "tým", "la skuádra", "La mia squadra vince.", "Můj tým vyhrává."],
  ["la palla", "míč", "la pála", "Passami la palla.", "Přihraj mi míč."],
  ["il libro", "kniha", "il líbro", "Leggo un bel libro.", "Čtu pěknou knihu."],
  ["il film", "film", "il film", "Guardo un film.", "Dívám se na film."],
  ["il cinema", "kino", "il čínema", "Vado al cinema.", "Jdu do kina."],
  ["il teatro", "divadlo", "il teátro", "Mi piace il teatro.", "Mám rád divadlo."],
  ["il museo", "muzeum", "il muzéo", "Visito il museo.", "Navštěvuji muzeum."],
  ["la musica", "hudba", "la múzika", "Ascolto la musica.", "Poslouchám hudbu."],
  ["il concerto", "koncert", "il končérto", "Vado al concerto.", "Jdu na koncert."],
  ["la chitarra", "kytara", "la kitára", "Suono la chitarra.", "Hraju na kytaru."],
  ["il pianoforte", "klavír", "il pjanofórte", "Il pianoforte è scordato.", "Klavír je rozladěný."],
  ["la fotografia", "fotografie", "la fotográfia", "Faccio una fotografia.", "Dělám fotku."],
  ["il viaggio", "cesta, výlet", "il vjádžo", "Faccio un bel viaggio.", "Dělám si pěkný výlet."],
  ["la spiaggia", "pláž", "la spjádža", "Vado in spiaggia.", "Jdu na pláž."],
  ["il mare", "moře", "il máre", "Il mare è calmo.", "Moře je klidné."],
  ["la montagna", "hora", "la montáňa", "Passeggio in montagna.", "Procházím se po horách."],
  ["il lago", "jezero", "il lágo", "Il lago è freddo.", "Jezero je studené."],
  ["il bosco", "les", "il bósko", "Cammino nel bosco.", "Jdu lesem."],
  ["il parco", "park", "il párko", "I bambini giocano nel parco.", "Děti si hrají v parku."],
  ["il videogioco", "videohra", "il videodžóko", "Gioco al videogioco.", "Hraju videohru."],
  ["il disegno", "kresba", "il dizéňo", "Faccio un disegno.", "Dělám kresbu."],
  ["la danza", "tanec", "la dánca", "La danza è la mia passione.", "Tanec je moje vášeň."],
  ["il canto", "zpěv", "il kánto", "Il canto mi rilassa.", "Zpěv mě uvolňuje."],
  ["la pesca", "rybaření", "la péska", "Vado a pesca.", "Jdu rybařit."],
  ["il campeggio", "kempování", "il kampédžo", "Andiamo in campeggio.", "Jedeme kempovat."]
];

// 4. Oblečení a móda
const obleceni = [
  ["i vestiti", "oblečení", "i vestíti", "Compro nuovi vestiti.", "Kupuji nové oblečení."],
  ["la maglietta", "tričko", "la maljéta", "La maglietta è blu.", "Tričko je modré."],
  ["la camicia", "košile", "la kamíča", "La camicia è elegante.", "Košile je elegantní."],
  ["il maglione", "svetr", "il maljóne", "Il maglione è caldo.", "Svetr je teplý."],
  ["i pantaloni", "kalhoty", "i pantalóni", "I pantaloni sono lunghi.", "Kalhoty jsou dlouhé."],
  ["i jeans", "džíny", "i džíns", "Indosso i jeans.", "Mám na sobě džíny."],
  ["i pantaloncini", "kraťasy", "i pantalončíni", "In estate metto i pantaloncini.", "V létě nosím kraťasy."],
  ["la gonna", "sukně", "la góna", "La gonna è corta.", "Sukně je krátká."],
  ["il vestito", "šaty (dámské) / oblek", "il vestíto", "Il vestito è rosso.", "Šaty jsou červené."],
  ["la giacca", "bunda, sako", "la džáka", "La giacca è di pelle.", "Bunda je kožená."],
  ["il cappotto", "kabát", "il kapóto", "In inverno metto il cappotto.", "V zimě nosím kabát."],
  ["l'impermeabile", "pláštěnka", "limpermeábile", "Piove, prendi l'impermeabile.", "Prší, vezmi si pláštěnku."],
  ["le scarpe", "boty", "le skárpe", "Le scarpe sono nuove.", "Boty jsou nové."],
  ["gli stivali", "kozačky", "lji stiváli", "Gli stivali sono neri.", "Kozačky jsou černé."],
  ["i sandali", "sandály", "i sándali", "Metto i sandali al mare.", "K moři si beru sandály."],
  ["le calze", "ponožky", "le kálce", "Le calze sono bucate.", "Ponožky jsou děravé."],
  ["la sciarpa", "šála", "la šárpa", "La sciarpa tiene caldo.", "Šála hřeje."],
  ["il cappello", "klobouk, čepice", "il kapélo", "Il cappello mi ripara dal sole.", "Klobouk mě chrání před sluncem."],
  ["i guanti", "rukavice", "i guánti", "Ho i guanti di lana.", "Mám vlněné rukavice."],
  ["la cintura", "pásek", "la čintúra", "La cintura è stretta.", "Pásek je úzký."],
  ["la cravatta", "kravata", "la kraváta", "La cravatta è elegante.", "Kravata je elegantní."],
  ["gli occhiali", "brýle", "lji okjáli", "Metto gli occhiali da sole.", "Nasazuji si sluneční brýle."],
  ["l'orologio", "hodinky", "lorolódžo", "L'orologio d'oro.", "Zlaté hodinky."],
  ["la borsa", "taška, kabelka", "la bórsa", "La borsa è pesante.", "Taška je těžká."],
  ["lo zaino", "batoh", "lo dzájno", "Lo zaino è pieno di libri.", "Batoh je plný knih."],
  ["l'ombrello", "deštník", "lombrélo", "Prendo l'ombrello perché piove.", "Beru deštník, protože prší."],
  ["l'anello", "prsten", "lanélo", "L'anello di diamanti.", "Diamantový prsten."],
  ["la collana", "náhrdelník", "la kolána", "Una collana di perle.", "Perlový náhrdelník."],
  ["il braccialetto", "náramek", "il bračaléto", "Il braccialetto d'argento.", "Stříbrný náramek."],
  ["gli orecchini", "náušnice", "lji orekíni", "Gli orecchini sono belli.", "Náušnice jsou hezké."]
];

// 5. Cestování
const cestovani = [
  ["il viaggio", "cesta, výlet", "il vjádžo", "Il viaggio è lungo.", "Cesta je dlouhá."],
  ["il biglietto", "jízdenka, letenka", "il biljéto", "Compro il biglietto.", "Kupuji jízdenku."],
  ["la valigia", "kufr", "la valídža", "Faccio la valigia.", "Balím kufr."],
  ["il passaporto", "pas", "il pasapórto", "Mostro il passaporto.", "Ukazuji pas."],
  ["la carta d'identità", "občanský průkaz", "la kárta didentitá", "Ecco la carta d'identità.", "Tady je občanka."],
  ["il turista", "turista", "il turísta", "Il turista scatta foto.", "Turista fotí."],
  ["l'hotel", "hotel", "lotél", "Dormo in hotel.", "Spím v hotelu."],
  ["la prenotazione", "rezervace", "la prenotacióne", "Ho una prenotazione.", "Mám rezervaci."],
  ["la vacanza", "dovolená", "la vakánca", "Vado in vacanza.", "Jedu na dovolenou."],
  ["la mappa", "mapa", "la mápa", "Guardo la mappa.", "Dívám se do mapy."],
  ["il treno", "vlak", "il tréno", "Il treno parte.", "Vlak odjíždí."],
  ["l'aereo", "letadlo", "laéreo", "L'aereo atterra.", "Letadlo přistává."],
  ["la nave", "loď", "la náve", "La nave è grande.", "Loď je velká."],
  ["l'autobus", "autobus", "lautobus", "Prendo l'autobus.", "Jedu autobusem."],
  ["la macchina", "auto", "la mákina", "Guido la macchina.", "Řídím auto."],
  ["la benzina", "benzín", "la bendzína", "Faccio benzina.", "Tankuji benzín."],
  ["il parcheggio", "parkoviště", "il parkédžo", "Cerco parcheggio.", "Hledám parkování."],
  ["la stazione", "nádraží", "la stacióne", "Vado alla stazione.", "Jdu na nádraží."],
  ["l'aeroporto", "letiště", "laeropórto", "Sono all'aeroporto.", "Jsem na letišti."],
  ["il volo", "let", "il vólo", "Il volo è cancellato.", "Let je zrušený."],
  ["il binario", "nástupiště", "il binárjo", "Il treno è al binario tre.", "Vlak je na třetím nástupišti."],
  ["il sedile", "sedadlo", "il sedíle", "Il mio sedile è vicino al finestrino.", "Mé sedadlo je u okna."],
  ["il finestrino", "okénko", "il finestríno", "Guardo fuori dal finestrino.", "Dívám se ven z okénka."],
  ["l'arrivo", "příjezd, přílet", "larívo", "L'arrivo è previsto alle dieci.", "Příjezd je plánován na desátou."],
  ["la partenza", "odjezd, odlet", "la parténca", "La partenza è in ritardo.", "Odjezd je zpožděný."],
  ["la frontiera", "hranice", "la frontjéra", "Attraverso la frontiera.", "Překračuji hranice."],
  ["il confine", "hranice", "il konfíne", "Il confine con la Francia.", "Hranice s Francií."],
  ["la lingua", "jazyk", "la língua", "Parlo due lingue.", "Mluvím dvěma jazyky."],
  ["la guida", "průvodce", "la guída", "La guida spiega la storia.", "Průvodce vysvětluje historii."],
  ["il souvenir", "suvenýr", "il suvenír", "Compro un souvenir.", "Kupuji suvenýr."]
];

// 6. Práce a povolání
const prace = [
  ["il lavoro", "práce", "il lavóro", "Vado al lavoro.", "Jdu do práce."],
  ["l'ufficio", "kancelář", "lufíčo", "Lavoro in ufficio.", "Pracuji v kanceláři."],
  ["l'azienda", "firma", "ladzjénda", "L'azienda è grande.", "Firma je velká."],
  ["il capo", "šéf", "il kápo", "Il capo è esigente.", "Šéf je náročný."],
  ["il collega", "kolega", "il koléga", "Il collega mi aiuta.", "Kolega mi pomáhá."],
  ["lo stipendio", "plat", "lo stipéndjo", "Lo stipendio è buono.", "Plat je dobrý."],
  ["la carriera", "kariéra", "la karjéra", "Fa carriera in fretta.", "Dělá rychle kariéru."],
  ["il medico", "lékař", "il médiko", "Il medico cura i malati.", "Lékař léčí nemocné."],
  ["l'infermiere", "zdravotní bratr", "linfermjére", "L'infermiere fa un'iniezione.", "Zdravotní bratr dává injekci."],
  ["l'insegnante", "učitel", "linseňánte", "L'insegnante spiega la lezione.", "Učitel vysvětluje lekci."],
  ["il poliziotto", "policista", "il policióto", "Il poliziotto ferma il ladro.", "Policista zastavuje zloděje."],
  ["il pompiere", "hasič", "il pompjére", "Il pompiere spegne il fuoco.", "Hasič hasí oheň."],
  ["l'avvocato", "advokát", "lavokáto", "L'avvocato difende il cliente.", "Advokát obhajuje klienta."],
  ["il giudice", "soudce", "il džúdiče", "Il giudice decide la sentenza.", "Soudce rozhoduje rozsudek."],
  ["l'attore", "herec", "latóre", "L'attore recita bene.", "Herec hraje dobře."],
  ["il cantante", "zpěvák", "il kantánte", "Il cantante ha una bella voce.", "Zpěvák má pěkný hlas."],
  ["il cuoco", "kuchař", "il kuóko", "Il cuoco prepara la cena.", "Kuchař připravuje večeři."],
  ["il cameriere", "číšník", "il kamerjére", "Il cameriere porta il menu.", "Číšník přináší menu."],
  ["il giornalista", "novinář", "il džornalísta", "Il giornalista scrive l'articolo.", "Novinář píše článek."],
  ["il fotografo", "fotograf", "il fotógrafo", "Il fotografo scatta foto.", "Fotograf dělá fotky."],
  ["l'autista", "řidič", "lautísta", "L'autista guida l'autobus.", "Řidič řídí autobus."],
  ["il meccanico", "mechanik", "il mekániko", "Il meccanico ripara l'auto.", "Mechanik opravuje auto."],
  ["l'ingegnere", "inženýr", "lindženjére", "L'ingegnere progetta il ponte.", "Inženýr navrhuje most."],
  ["l'architetto", "architekt", "larkitéto", "L'architetto disegna la casa.", "Architekt kreslí dům."],
  ["il contadino", "zemědělec", "il kontadíno", "Il contadino lavora nel campo.", "Zemědělec pracuje na poli."],
  ["l'operaio", "dělník", "loperájo", "L'operaio lavora in fabbrica.", "Dělník pracuje v továrně."],
  ["il commesso", "prodavač", "il koméso", "Il commesso vende i vestiti.", "Prodavač prodává oblečení."],
  ["il panettiere", "pekař", "il panetjére", "Il panettiere fa il pane.", "Pekař dělá chleba."],
  ["il sarto", "krejčí", "il sárto", "Il sarto cuce il vestito.", "Krejčí šije šaty."],
  ["il parrucchiere", "kadeřník", "il parukjére", "Il parrucchiere taglia i capelli.", "Kadeřník stříhá vlasy."],
  ["il programmatore", "programátor", "il programatóre", "Il programmatore scrive il codice.", "Programátor píše kód."],
  ["il segretario", "sekretář", "il segretárjo", "Il segretario risponde al telefono.", "Sekretář odpovídá na telefon."]
];


// 7. Fráze a Gramatika a Základy (Kombinovaný mega blok)
const fraze_zaklady = [
  ["Buongiorno", "Dobrý den / Dobré ráno", "buondžórno", "Buongiorno a tutti.", "Dobrý den všem."],
  ["Buonasera", "Dobrý večer", "buonaséra", "Buonasera, signore.", "Dobrý večer, pane."],
  ["Buonanotte", "Dobrou noc", "buonanóte", "Buonanotte, sogni d'oro.", "Dobrou noc, sladké sny."],
  ["Arrivederci", "Na shledanou", "arivedérči", "Arrivederci, a domani.", "Na shledanou, do zítra."],
  ["Ciao", "Ahoj", "čáo", "Ciao, come stai?", "Ahoj, jak se máš?"],
  ["Come stai?", "Jak se máš?", "kóme staj", "Ciao, come stai?", "Ahoj, jak se máš?"],
  ["Sto bene", "Mám se dobře", "sto béne", "Sto bene, grazie.", "Mám se dobře, díky."],
  ["Come ti chiami?", "Jak se jmenuješ?", "kóme ti kjámi", "Come ti chiami?", "Jak se jmenuješ?"],
  ["Mi chiamo", "Jmenuji se", "mi kjámo", "Mi chiamo Marco.", "Jmenuji se Marco."],
  ["Piacere", "Těší mě", "pjačére", "Piacere di conoscerti.", "Těší mě, že tě poznávám."],
  ["Per favore", "Prosím", "per favóre", "Un caffè, per favore.", "Kávu, prosím."],
  ["Grazie", "Děkuji", "grácje", "Grazie mille.", "Děkuji mockrát."],
  ["Prego", "Prosím (není zač)", "prégo", "Prego, figurati.", "Prosím, to nic není."],
  ["Scusa", "Promiň", "skúza", "Scusa, non volevo.", "Promiň, nechtěl jsem."],
  ["Mi dispiace", "Je mi to líto", "mi dispjáče", "Mi dispiace molto.", "Je mi to moc líto."],
  ["Sì", "Ano", "sì", "Sì, lo voglio.", "Ano, chci to."],
  ["No", "Ne", "no", "No, non posso.", "Ne, nemůžu."],
  ["Non capisco", "Nerozumím", "non kapísko", "Scusa, non capisco.", "Promiň, nerozumím."],
  ["Non lo so", "Nevím", "non lo so", "Non lo so esattamente.", "Nevím to přesně."],
  ["Può ripetere?", "Můžete to zopakovat?", "puó ripétere", "Può ripetere, per favore?", "Můžete to zopakovat, prosím?"],
  ["Parla inglese?", "Mluvíte anglicky?", "párla ingléze", "Scusi, parla inglese?", "Promiňte, mluvíte anglicky?"],
  ["Aiuto!", "Pomoc!", "ajúto", "Aiuto! Al ladro!", "Pomoc! Zloděj!"],
  ["Dov'è il bagno?", "Kde je záchod?", "dové il báňo", "Scusi, dov'è il bagno?", "Promiňte, kde je záchod?"],
  ["Quanto costa?", "Kolik to stojí?", "kuánto kósta", "Quanto costa questo?", "Kolik tohle stojí?"],
  ["Il conto", "Účet", "il kónto", "Il conto, per favore.", "Účet, prosím."],
  ["A presto", "Brzy na viděnou", "a présto", "A presto, amico mio.", "Brzy na viděnou, příteli."],
  ["Io", "Já", "ío", "Io sono ceco.", "Já jsem Čech."],
  ["Tu", "Ty", "tu", "Tu sei italiano.", "Ty jsi Ital."],
  ["Lui", "On", "luj", "Lui è mio fratello.", "On je můj bratr."],
  ["Lei", "Ona", "lej", "Lei è mia sorella.", "Ona je moje sestra."],
  ["Noi", "My", "noj", "Noi andiamo a casa.", "My jdeme domů."],
  ["Voi", "Vy", "voj", "Voi siete amici.", "Vy jste přátelé."],
  ["Loro", "Oni / Ony", "lóro", "Loro mangiano la pizza.", "Oni jedí pizzu."],
  ["Mio", "Můj", "mío", "Questo è mio.", "Tohle je moje."],
  ["Tuo", "Tvůj", "túo", "È il tuo libro?", "Je to tvá kniha?"],
  ["Suo", "Jeho / Její", "súo", "Il suo nome è Paolo.", "Jeho jméno je Paolo."],
  ["Nostro", "Náš", "nóstro", "La nostra casa.", "Náš dům."],
  ["Vostro", "Váš", "vóstro", "La vostra scuola.", "Vaše škola."],
  ["Loro (přivlastňovací)", "Jejich", "lóro", "La loro auto.", "Jejich auto."],
  ["Questo", "Tento", "kuésto", "Questo è bello.", "Tohle je hezké."],
  ["Quello", "Tamten", "kuélo", "Quello è lontano.", "Tamto je daleko."],
  ["Qui", "Tady", "kuí", "Vieni qui.", "Pojď sem."],
  ["Lì", "Tam", "lí", "Guarda lì.", "Podívej se tam."],
  ["Oggi", "Dnes", "ódži", "Oggi piove.", "Dnes prší."],
  ["Sempre", "Vždy", "sémpre", "Io sono sempre felice.", "Já jsem vždy šťastný."],
  ["Mai", "Nikdy", "maj", "Non dico mai bugie.", "Nikdy neříkám lži."],
  ["Molto", "Velmi / Hodně", "mólto", "È molto buono.", "Je to velmi dobré."],
  ["Poco", "Málo", "póko", "Mangio poco.", "Jím málo."],
  ["Tutto", "Všechno", "túto", "Tutto va bene.", "Všechno jde dobře."],
  ["Niente", "Nic", "njénte", "Non fa niente.", "To nevadí (Nedělá to nic)."],
  ["Perché", "Proč / Protože", "perké", "Perché piangi?", "Proč pláčeš?"],
  ["Quando", "Kdy", "kuándo", "Quando arrivi?", "Kdy přijedeš?"],
  ["Dove", "Kde", "dóve", "Dove abiti?", "Kde bydlíš?"],
  ["Chi", "Kdo", "ki", "Chi sei?", "Kdo jsi?"],
  ["Cosa", "Co", "kóza", "Cosa fai?", "Co děláš?"],
  ["Come", "Jak", "kóme", "Come funziona?", "Jak to funguje?"],
  ["E", "A (spojka)", "e", "Tu e io.", "Ty a já."],
  ["Ma", "Ale", "ma", "Bello ma costoso.", "Hezké, ale drahé."],
  ["O", "Nebo", "o", "Vero o falso?", "Pravda nebo lež?"],
  ["Se", "Jestliže / Pokud", "se", "Se piove, non esco.", "Pokud prší, nejdu ven."]
];

// Přidání nových kategorií
addWords("Tělo a zdraví", "A1", telo);
addWords("Dům a domácnost", "A1", dum);
addWords("Volný čas a sport", "A1", sport);
addWords("Oblečení a móda", "A1", obleceni);
addWords("Cestování", "A1", cestovani);
addWords("Práce a povolání", "A1", prace);

// Rozdělíme fráze a základy a gramatiku
addWords("Základy", "A1", fraze_zaklady.slice(0, 15));
addWords("Fráze", "A1", fraze_zaklady.slice(15, 30));
addWords("Gramatika", "A1", fraze_zaklady.slice(30));

fs.writeFileSync(path.join(__dirname, 'massive_words_2.json'), JSON.stringify(words, null, 2));
console.log(`Generated ${words.length} MORE massive words!`);
