#!/usr/bin/env node
// Generátor ~928 nových italských slovíček do deficitních kategorií
// Každá kategorie bude mít min. 100 slov

const words = [];

const add = (italian, czech, category, difficulty, pronunciation, example_it, example_cz) => {
  words.push({ italian, czech, category, difficulty, pronunciation, example_it, example_cz });
};

// ═══════════════════════════════════════════════════════
// ZÁKLADY (+69) — cíl: 100
// ═══════════════════════════════════════════════════════
add("sì","ano","Základy","A1","si","Sì, capisco.","Ano, rozumím.");
add("no","ne","Základy","A1","no","No, grazie.","Ne, děkuji.");
add("forse","možná","Základy","A1","for-se","Forse domani.","Možná zítra.");
add("subito","hned","Základy","A1","su-bi-to","Vengo subito.","Přijdu hned.");
add("già","již/už","Základy","A1","dʒa","Ho già mangiato.","Už jsem jedl.");
add("ancora","ještě/znovu","Základy","A1","an-ko-ra","Ancora una volta.","Ještě jednou.");
add("mai","nikdy","Základy","A1","mai","Non lo faccio mai.","To nikdy nedělám.");
add("sempre","vždy","Základy","A1","sem-pre","Sei sempre gentile.","Jsi vždy laskavý.");
add("spesso","často","Základy","A1","spes-so","Vado spesso al cinema.","Často chodím do kina.");
add("adesso","nyní","Základy","A1","a-des-so","Adesso capisco.","Nyní rozumím.");
add("poi","pak/poté","Základy","A1","poi","Prima mangio, poi studio.","Nejdřív jím, pak studuji.");
add("prima","nejdříve","Základy","A1","pri-ma","Prima di tutto.","Především.");
add("dopo","po/potom","Základy","A1","do-po","Ci vediamo dopo.","Uvidíme se potom.");
add("insieme","společně","Základy","A1","in-sje-me","Andiamo insieme.","Jdeme spolu.");
add("solo","sám/jen","Základy","A1","so-lo","Vivo solo.","Žiji sám.");
add("abbastanza","dost","Základy","A1","ab-bas-tan-dza","Ne ho abbastanza.","Mám toho dost.");
add("troppo","příliš","Základy","A1","trop-po","È troppo caldo.","Je příliš horko.");
add("poco","málo","Základy","A1","po-ko","Parla poco.","Mluví málo.");
add("molto","hodně","Základy","A1","mol-to","Mi piace molto.","Mám to rád.");
add("tutto","vše","Základy","A1","tut-to","Ho capito tutto.","Pochopil jsem vše.");
add("niente","nic","Základy","A1","njen-te","Non voglio niente.","Nechci nic.");
add("qualcosa","něco","Základy","A1","kwal-ko-za","Vuoi qualcosa?","Chceš něco?");
add("qualcuno","někdo","Základy","A1","kwal-ku-no","C'è qualcuno?","Je tu někdo?");
add("nessuno","nikdo","Základy","A1","nes-su-no","Non c'è nessuno.","Není tu nikdo.");
add("anche","také","Základy","A1","an-ke","Anch'io vengo.","Také přijdu.");
add("però","ale/přesto","Základy","A1","pe-ro","Mi piace, però è caro.","Líbí se mi, ale je to drahé.");
add("quindi","tedy","Základy","A1","kwin-di","Quindi vieni?","Tedy přijdeš?");
add("perché","proč/protože","Základy","A1","per-ke","Perché non vieni?","Proč nepřijdeš?");
add("come","jak/jako","Základy","A1","ko-me","Come stai?","Jak se máš?");
add("dove","kde","Základy","A1","do-ve","Dove sei?","Kde jsi?");
add("quando","kdy","Základy","A1","kwan-do","Quando arrivi?","Kdy přijdeš?");
add("quanto","kolik","Základy","A1","kwan-to","Quanto costa?","Kolik to stojí?");
add("chi","kdo","Základy","A1","ki","Chi sei?","Kdo jsi?");
add("che cosa","co","Základy","A1","ke ko-za","Che cosa fai?","Co děláš?");
add("un po'","trochu","Základy","A1","un po","Parla un po' lentamente.","Mluv trochu pomalu.");
add("davvero","opravdu","Základy","A1","dav-ve-ro","Davvero? Non ci credo.","Opravdu? Tomu nevěřím.");
add("certo","jistě/samozřejmě","Základy","A1","cher-to","Certo, con piacere.","Jistě, s radostí.");
add("ecco","tady/hle","Základy","A1","ek-ko","Ecco il tuo caffè.","Tady je tvá káva.");
add("va bene","dobře/v pořádku","Základy","A1","va be-ne","Va bene, ci vediamo.","Dobře, uvidíme se.");
add("prego","prosím/není zač","Základy","A1","pre-go","Prego, si accomodi.","Prosím, posaďte se.");
add("scusi","promiňte (formální)","Základy","A1","sku-zi","Scusi, dov'è la stazione?","Promiňte, kde je nádraží?");
add("grazie mille","velmi děkuji","Základy","A1","gra-tsje mil-le","Grazie mille per l'aiuto.","Velmi vám děkuji za pomoc.");
add("piacere mio","potěšení na mé straně","Základy","A1","pja-che-re mi-o","Piacere mio!","Těší mě!");
add("a presto","brzy na shledanou","Základy","A1","a pres-to","Ci vediamo, a presto!","Uvidíme se, na brzkou shledanou!");
add("a domani","na shledanou zítra","Základy","A1","a do-ma-ni","Ciao, a domani!","Ahoj, na shledanou zítra!");
add("buona fortuna","hodně štěstí","Základy","A1","bwo-na for-tu-na","Buona fortuna all'esame!","Hodně štěstí u zkoušky!");
add("auguri","gratulace/přání","Základy","A1","au-gu-ri","Auguri per il tuo compleanno!","Gratulace k narozeninám!");
add("salute","na zdraví/zdraví","Základy","A1","sa-lu-te","Salute! Cin cin!","Na zdraví!");
add("mi dispiace","je mi líto","Základy","A1","mi dis-pja-che","Mi dispiace molto.","Je mi velmi líto.");
add("sono d'accordo","souhlasím","Základy","A2","so-no dak-kor-do","Sono d'accordo con te.","Souhlasím s tebou.");
add("non capisco","nerozumím","Základy","A1","non ka-pis-ko","Non capisco, può ripetere?","Nerozumím, může opakovat?");
add("può parlare lentamente","může mluvit pomalu","Základy","A1","pwo par-la-re len-ta-men-te","Può parlare lentamente?","Může mluvit pomalu?");
add("come si dice","jak se říká","Základy","A1","ko-me si di-che","Come si dice in italiano?","Jak se to řekne italsky?");
add("che ora è","kolik je hodin","Základy","A1","ke o-ra e","Che ora è adesso?","Kolik je teď hodin?");
add("il numero","číslo","Základy","A1","il nu-me-ro","Qual è il tuo numero?","Jaké je tvé číslo?");
add("la parola","slovo","Základy","A1","la pa-ro-la","Non conosco questa parola.","Neznám toto slovo.");
add("la frase","věta","Základy","A1","la fra-ze","Scrivi una frase.","Napiš větu.");
add("l'italiano","italština","Základy","A1","li-ta-lja-no","Studio l'italiano.","Studuji italštinu.");
add("lo straniero","cizinec","Základy","A2","lo stra-nje-ro","Sono uno straniero.","Jsem cizinec.");
add("il passaporto","cestovní pas","Základy","A1","il pas-sa-por-to","Ho il passaporto.","Mám pas.");
add("il biglietto","lístek/vstupenka","Základy","A1","il bil-let-to","Dov'è il mio biglietto?","Kde je můj lístek?");
add("l'informazione","informace","Základy","A1","lin-for-ma-tsjo-ne","Ho bisogno di informazioni.","Potřebuji informace.");
add("l'aiuto","pomoc","Základy","A1","la-ju-to","Ho bisogno di aiuto.","Potřebuji pomoc.");
add("il problema","problém","Základy","A1","il pro-ble-ma","Ho un problema.","Mám problém.");
add("la risposta","odpověď","Základy","A1","la ris-pos-ta","Non conosco la risposta.","Neznám odpověď.");
add("la domanda","otázka","Základy","A1","la do-man-da","Faccio una domanda.","Pokládám otázku.");
add("il motivo","důvod","Základy","A2","il mo-ti-vo","Qual è il motivo?","Jaký je důvod?");
add("la differenza","rozdíl","Základy","A2","la dif-fe-ren-dza","Qual è la differenza?","Jaký je rozdíl?");

// ═══════════════════════════════════════════════════════
// BARVY (+69) — cíl: 100
// ═══════════════════════════════════════════════════════
add("bordeaux","vínová","Barvy","A2","bor-do","Una borsa bordeaux.","Vínová kabelka.");
add("turchese","tyrkysová","Barvy","A2","tur-ke-ze","Il mare è turchese.","Moře je tyrkysové.");
add("indaco","indigo","Barvy","A2","in-da-ko","Un abito indaco.","Indigo šaty.");
add("avorio","slonovinová","Barvy","A2","a-vjo-ro","Un vestito avorio.","Šaty slonovinové barvy.");
add("corallo","korálová","Barvy","A2","ko-ral-lo","Labbra color corallo.","Korálové rty.");
add("color acqua","barva vody","Barvy","A2","ko-lor ak-wa","Un top color acqua.","Tílko barvy vody.");
add("color miele","medová barva","Barvy","A2","ko-lor mje-le","Capelli color miele.","Medové vlasy.");
add("dorato","zlatavý","Barvy","A2","do-ra-to","Un anello dorato.","Zlatavý prsten.");
add("argentato","stříbrný","Barvy","A2","ar-dʒen-ta-to","Una cornice argentata.","Stříbrný rámeček.");
add("ramato","měděný","Barvy","A2","ra-ma-to","Capelli ramati.","Měděné vlasy.");
add("ruggine","rezavý","Barvy","A2","rud-dʒi-ne","Un colore ruggine.","Rezavá barva.");
add("ocra","okrová","Barvy","A2","ok-ra","Una parete ocra.","Okrová stěna.");
add("tabacco","tabáková","Barvy","A2","ta-bak-ko","Un cappotto tabacco.","Tabákový kabát.");
add("cipria","pudrová","Barvy","A2","chip-rja","Una tenda cipria.","Pudrová záclona.");
add("glicine","šeříkový","Barvy","A2","gli-chi-ne","Un abito glicine.","Šeříkové šaty.");
add("ciclamino","cyklámenový","Barvy","A2","chi-kla-mi-no","Un fiore ciclamino.","Cyklámenový květ.");
add("fucsia","fuchsiový","Barvy","A2","fuk-sja","Un cappello fucsia.","Fuchsiový klobouk.");
add("pesca","broskvová","Barvy","A2","pes-ka","Una gonna pesca.","Broskvová sukně.");
add("salmone","lososový","Barvy","A2","sal-mo-ne","Un vestito salmone.","Lososové šaty.");
add("mattone","cihlový","Barvy","A2","mat-to-ne","Un muro mattone.","Cihlová zeď.");
add("terracotta","terakota","Barvy","A2","ter-ra-kot-ta","Un vaso terracotta.","Terakotový hrnec.");
add("kaki","khaki","Barvy","A2","ka-ki","Un pantalone kaki.","Khaki kalhoty.");
add("militare","vojenská zelená","Barvy","A2","mi-li-ta-re","Un giubbotto militare.","Vojensky zelená bunda.");
add("lime","limetková","Barvy","A2","laim","Un colore lime.","Limetková barva.");
add("menta","mentolová","Barvy","A2","men-ta","Un vestito menta.","Mentolové šaty.");
add("petrolio","petrolejová","Barvy","A2","pe-tro-ljo","Una giacca petrolio.","Petrolejová bunda.");
add("celeste","světle modrá","Barvy","A1","che-les-te","Un cielo celeste.","Světle modré nebe.");
add("cobalto","kobaltová","Barvy","A2","ko-bal-to","Un blu cobalto.","Kobaltová modř.");
add("notte","noční modrá","Barvy","A2","not-te","Un abito blu notte.","Šaty noční modři.");
add("chiaro","světlý","Barvy","A1","kja-ro","Un colore chiaro.","Světlá barva.");
add("scuro","tmavý","Barvy","A1","sku-ro","Un colore scuro.","Tmavá barva.");
add("pallido","bledý","Barvy","A2","pal-li-do","Un viso pallido.","Bledý obličej.");
add("vivo","živý/sytý","Barvy","A2","vi-vo","Un colore vivo.","Sytá barva.");
add("opaco","matný","Barvy","A2","o-pa-ko","Una vernice opaca.","Matný lak.");
add("brillante","lesklý","Barvy","A2","bril-lan-te","Un colore brillante.","Lesklá barva.");
add("neutro","neutrální","Barvy","A2","neu-tro","Un colore neutro.","Neutrální barva.");
add("pastello","pastelový","Barvy","A2","pas-tel-lo","Un colore pastello.","Pastelová barva.");
add("fluorescente","fluorescenční","Barvy","B1","flu-o-res-chen-te","Un giubbino fluorescente.","Fluorescenční vesta.");
add("trasparente","průhledný","Barvy","A2","tras-pa-ren-te","Un vetro trasparente.","Průhledné sklo.");
add("multicolore","vícebarevný","Barvy","A2","mul-ti-ko-lo-re","Un vestito multicolore.","Vícebarevné šaty.");
add("monocromatico","jednobarevný","Barvy","B1","mo-no-kro-ma-ti-ko","Un look monocromatico.","Jednobarevný look.");
add("beige scuro","tmavě béžový","Barvy","A2","beiʒ sku-ro","Un cappotto beige scuro.","Tmavě béžový kabát.");
add("verde salvia","šalvějová zelená","Barvy","A2","ver-de sal-vja","Un muro verde salvia.","Zeď šalvějové zeleně.");
add("verde bosco","lesní zelená","Barvy","A2","ver-de bos-ko","Un maglione verde bosco.","Svetr lesní zeleně.");
add("azzurro polvere","prašně modrá","Barvy","A2","ad-dzur-ro pol-ve-re","Un cielo azzurro polvere.","Prašně modré nebe.");
add("bianco sporco","špinavě bílý","Barvy","A2","bjan-ko spor-ko","Un muro bianco sporco.","Stěna špinavě bílé.");
add("grigio perla","perleťová šedá","Barvy","A2","gri-dʒo per-la","Una giacca grigio perla.","Bunda perleťové šedi.");
add("grigio fumo","kouřová šedá","Barvy","A2","gri-dʒo fu-mo","Un abito grigio fumo.","Šaty kouřové šedé.");
add("marrone chiaro","světle hnědá","Barvy","A1","mar-ro-ne kja-ro","Un tavolo marrone chiaro.","Světle hnědý stůl.");
add("rosso mattone","cihlová červená","Barvy","A2","ros-so mat-to-ne","Una porta rosso mattone.","Cihlově červené dveře.");
add("giallo ocra","okrově žlutá","Barvy","A2","dʒal-lo ok-ra","Una parete giallo ocra.","Okrově žlutá stěna.");
add("verde acqua","akvamarínová","Barvy","A2","ver-de ak-wa","Una piscina verde acqua.","Akvamarínový bazén.");
add("lilla","fialová lila","Barvy","A2","lil-la","Un fiocco lilla.","Fialová mašle.");
add("prugna","švestková","Barvy","A2","pru-nja","Un abito color prugna.","Švestkové šaty.");
add("amaranto","amarantová","Barvy","A2","a-ma-ran-to","Un rosso amaranto.","Amarantová červeň.");
add("lavanda","levandulová","Barvy","A2","la-van-da","Un campo lavanda.","Levandulové pole.");
add("pervinca","pomněnkově modrá","Barvy","A2","per-vin-ka","Un blu pervinca.","Pomněnkově modrá.");
add("cachi","kakiový","Barvy","A2","ka-ki","Un cachi chiaro.","Světlá khaki.");
add("tortora","holubičí šedá","Barvy","A2","tor-to-ra","Un grigio tortora.","Holubičí šedá.");
add("sabbia","pískový","Barvy","A2","sab-bja","Un colore sabbia.","Pískový odstín.");
add("vaniglia","vanilkový","Barvy","A2","va-nil-ja","Un bianco vaniglia.","Vanilková bílá.");
add("cioccolato","čokoládový","Barvy","A1","chok-ko-la-to","Un marrone cioccolato.","Čokoládová hnědá.");
add("caramello","karamelový","Barvy","A2","ka-ra-mel-lo","Capelli caramello.","Karamelové vlasy.");
add("ruggine chiaro","světle rezavý","Barvy","A2","rud-dʒi-ne kja-ro","Un rosso ruggine chiaro.","Světle rezavá.");
add("verde oliva","olivový","Barvy","A1","ver-de o-li-va","Un verde oliva scuro.","Tmavě olivová.");
add("blu notte","temně modrá","Barvy","A2","blu not-te","Un blu notte profondo.","Temně modrá.");
add("rosato","narůžovělý","Barvy","A2","ro-za-to","Un vino rosato.","Narůžovělé víno.");
add("écru","přírodní bílá","Barvy","A2","e-kru","Un tessuto écru.","Přírodní tkanina.");
add("mogano","mahagonový","Barvy","A2","mo-ga-no","Un legno mogano.","Mahagonové dřevo.");

// ═══════════════════════════════════════════════════════
// POČASÍ (+70) — cíl: 100
// ═══════════════════════════════════════════════════════
add("il cielo","nebe","Počasí","A1","il chje-lo","Il cielo è azzurro.","Nebe je modré.");
add("la nuvola","mrak","Počasí","A1","la nu-vo-la","Le nuvole sono scure.","Mraky jsou tmavé.");
add("la pioggia","déšť","Počasí","A1","la pjod-dʒa","Cade la pioggia.","Prší.");
add("la neve","sníh","Počasí","A1","la ne-ve","La neve è bianca.","Sníh je bílý.");
add("il vento","vítr","Počasí","A1","il ven-to","Il vento è forte.","Vítr je silný.");
add("la tempesta","bouře","Počasí","A1","la tem-pes-ta","C'è una tempesta.","Je bouře.");
add("il fulmine","blesk","Počasí","A1","il ful-mi-ne","Ho paura dei fulmini.","Bojím se blesků.");
add("il tuono","hrom","Počasí","A1","il tuo-no","Sento i tuoni.","Slyším hřmění.");
add("la grandine","kroupy","Počasí","A2","la gran-di-ne","È caduta la grandine.","Padaly kroupy.");
add("la nebbia","mlha","Počasí","A1","la neb-bja","C'è molta nebbia.","Je hustá mlha.");
add("la bruma","opar/mžení","Počasí","A2","la bru-ma","Una leggera bruma.","Lehký opar.");
add("il ghiaccio","led","Počasí","A2","il gjat-cho","Attenzione al ghiaccio!","Pozor na led!");
add("la brina","jinovatka","Počasí","A2","la bri-na","La brina sul prato.","Jinovatka na trávníku.");
add("la rugiada","rosa","Počasí","A2","la ru-dʒa-da","La rugiada del mattino.","Ranní rosa.");
add("il sole","slunce","Počasí","A1","il so-le","Splende il sole.","Svítí slunce.");
add("la luna","měsíc","Počasí","A1","la lu-na","La luna piena.","Úplněk.");
add("le stelle","hvězdy","Počasí","A1","le stel-le","Le stelle brillano.","Hvězdy září.");
add("l'arcobaleno","duha","Počasí","A1","lar-ko-ba-le-no","Dopo la pioggia c'è l'arcobaleno.","Po dešti je duha.");
add("la foschia","zákal/mlha","Počasí","A2","la fos-kja","Cammino nella foschia.","Chodím v zákalku.");
add("l'alluvione","záplava","Počasí","A2","lal-lu-vjo-ne","L'alluvione ha colpito il paese.","Záplava zasáhla obec.");
add("la siccità","sucho","Počasí","A2","la sit-chi-ta","La siccità estiva.","Letní sucho.");
add("l'uragano","uragán","Počasí","A2","lu-ra-ga-no","Un uragano tropicale.","Tropický uragán.");
add("il tornado","tornádo","Počasí","A2","il tor-na-do","Un tornado devastante.","Ničivé tornádo.");
add("la tormenta","sněhová bouře","Počasí","A2","la tor-men-ta","Una tormenta di neve.","Sněhová bouře.");
add("la valanga","lavina","Počasí","A2","la va-lan-ga","Una valanga sulle Alpi.","Lavina v Alpách.");
add("l'onda di calore","vlna veder","Počasí","B1","lon-da di ka-lo-re","Un'onda di calore estiva.","Letní vlna veder.");
add("fresco","svěží/čerstvý","Počasí","A1","fres-ko","L'aria è fresca.","Vzduch je svěží.");
add("umido","vlhký","Počasí","A1","u-mi-do","Il clima è umido.","Klima je vlhké.");
add("secco","suchý","Počasí","A1","sek-ko","L'aria è secca.","Vzduch je suchý.");
add("afoso","dusný","Počasí","A2","a-fo-zo","Una giornata afosa.","Dusný den.");
add("nuvoloso","oblačný","Počasí","A1","nu-vo-lo-zo","Il cielo è nuvoloso.","Nebe je zatažené.");
add("sereno","jasný","Počasí","A1","se-re-no","Il tempo è sereno.","Počasí je jasné.");
add("piovoso","deštivý","Počasí","A1","pjo-vo-zo","Una giornata piovosa.","Deštivý den.");
add("nevoso","sněžný","Počasí","A1","ne-vo-zo","Un inverno nevoso.","Sněhová zima.");
add("ventoso","větrný","Počasí","A1","ven-to-zo","Un giorno ventoso.","Větrný den.");
add("gelido","mrazivý","Počasí","A2","dʒe-li-do","Un freddo gelido.","Mrazivý chlad.");
add("torrido","pálivý","Počasí","A2","tor-ri-do","Un caldo torrido.","Pálivé horko.");
add("temperato","mírný","Počasí","A2","tem-pe-ra-to","Un clima temperato.","Mírné podnebí.");
add("subtropicale","subtropický","Počasí","B1","sub-tro-pi-ka-le","Un clima subtropicale.","Subtropické podnebí.");
add("la previsione","předpověď","Počasí","A2","la pre-vi-zjo-ne","Le previsioni del tempo.","Předpověď počasí.");
add("la temperatura","teplota","Počasí","A1","la tem-pe-ra-tu-ra","La temperatura massima.","Maximální teplota.");
add("il termometro","teploměr","Počasí","A1","il ter-mo-me-tro","Il termometro segna 30°.","Teploměr ukazuje 30°.");
add("gradi","stupně","Počasí","A1","gra-di","Ci sono trenta gradi.","Je třicet stupňů.");
add("l'ombrello","deštník","Počasí","A1","lom-brel-lo","Prendi l'ombrello.","Vezmi deštník.");
add("l'impermeabile","pláštěnka","Počasí","A2","lim-per-mea-bi-le","Metti l'impermeabile.","Oblékni pláštěnku.");
add("i guanti","rukavice","Počasí","A1","i gwan-ti","Metti i guanti.","Oblékni rukavice.");
add("la sciarpa","šátek","Počasí","A1","la shchar-pa","Ho freddo, prendo la sciarpa.","Je mi zima, vezmu šátek.");
add("l'estate","léto","Počasí","A1","les-ta-te","In estate fa caldo.","V létě je teplo.");
add("l'autunno","podzim","Počasí","A1","lau-tun-no","In autunno cadono le foglie.","Na podzim padají listy.");
add("l'inverno","zima","Počasí","A1","lin-ver-no","L'inverno è freddo.","Zima je studená.");
add("la primavera","jaro","Počasí","A1","la pri-ma-ve-ra","In primavera fioriscono i fiori.","Na jaře kvetou květiny.");
add("le precipitazioni","srážky","Počasí","B1","le pre-chi-pi-ta-tsjo-ni","Le precipitazioni abbondanti.","Vydatné srážky.");
add("l'umidità","vlhkost","Počasí","A2","lu-mi-di-ta","L'umidità relativa.","Relativní vlhkost.");
add("la pressione","tlak","Počasí","A2","la pres-sjo-ne","La pressione atmosferica.","Atmosférický tlak.");
add("il barometro","barometr","Počasí","B1","il ba-ro-me-tro","Il barometro scende.","Barometr klesá.");
add("il clima","klima","Počasí","A1","il kli-ma","Il clima mediterraneo.","Středomořské klima.");
add("le stagioni","roční období","Počasí","A1","le sta-dʒo-ni","Le quattro stagioni.","Čtyři roční období.");
add("piovere","pršet","Počasí","A1","pjo-ve-re","Oggi piove.","Dnes prší.");
add("nevicare","sněžit","Počasí","A1","ne-vi-ka-re","Sta nevicando.","Sněží.");
add("tirare vento","foukat","Počasí","A1","ti-ra-re ven-to","Tira molto vento.","Velmi fouká.");
add("fare bel tempo","být hezké počasí","Počasí","A1","fa-re bel tem-po","Fa bel tempo oggi.","Dnes je hezké počasí.");
add("fare brutto tempo","být ošklivé počasí","Počasí","A1","fa-re brut-to tem-po","Fa brutto tempo.","Je ošklivé počasí.");
add("il cambiamento climatico","klimatická změna","Počasí","B1","il kam-bja-men-to kli-ma-ti-ko","Il cambiamento climatico è reale.","Klimatická změna je realita.");
add("il riscaldamento globale","globální oteplování","Počasí","B1","il ris-kal-da-men-to glo-ba-le","Il riscaldamento globale preoccupa.","Globální oteplování znepokojuje.");
add("l'inquinamento","znečištění","Počasí","A2","lin-kwi-na-men-to","L'inquinamento dell'aria.","Znečištění ovzduší.");
add("la tromba d'aria","vichr","Počasí","B1","la trom-ba da-rja","Una tromba d'aria ha colpito.","Vichr udeřil.");
add("la corrente d'aria","průvan","Počasí","A2","la kor-ren-te da-rja","C'è una corrente d'aria.","Je průvan.");
add("gelare","mrazit","Počasí","A2","dʒe-la-re","Stanotte gela.","Dnes v noci bude mrznout.");
add("sgelare","rozmrznout","Počasí","A2","zdʒe-la-re","Il ghiaccio si sgela.","Led taje.");

// ═══════════════════════════════════════════════════════
// ŠKOLA A PRÁCE (+73) — cíl: 100
// ═══════════════════════════════════════════════════════
add("la scuola","škola","Škola a práce","A1","la skwo-la","Vado a scuola ogni giorno.","Chodím do školy každý den.");
add("la classe","třída","Škola a práce","A1","la klas-se","La classe è grande.","Třída je velká.");
add("l'aula","učebna","Škola a práce","A1","lau-la","L'aula è silenziosa.","Učebna je tichá.");
add("la lavagna","tabule","Škola a práce","A1","la la-van-ja","Il professore scrive sulla lavagna.","Profesor píše na tabuli.");
add("il quaderno","sešit","Škola a práce","A1","il kwa-der-no","Apro il quaderno.","Otevírám sešit.");
add("la penna","pero","Škola a práce","A1","la pen-na","Presta la tua penna.","Půjč mi pero.");
add("la matita","tužka","Škola a práce","A1","la ma-ti-ta","Scrivo con la matita.","Píšu tužkou.");
add("la gomma","guma/pryž","Škola a práce","A1","la gom-ma","Ho bisogno della gomma.","Potřebuji gumu.");
add("il righello","pravítko","Škola a práce","A1","il ri-gel-lo","Traccia una linea col righello.","Nakresli čáru pravítkem.");
add("il compasso","kružítko","Škola a práce","A2","il kom-pas-so","Disegna un cerchio col compasso.","Nakresli kruh kružítkem.");
add("il libro","kniha","Škola a práce","A1","il li-bro","Leggo un libro.","Čtu knihu.");
add("il dizionario","slovník","Škola a práce","A1","il di-tsjo-na-rjo","Uso il dizionario.","Používám slovník.");
add("il computer","počítač","Škola a práce","A1","il kom-pju-ter","Uso il computer a scuola.","Používám počítač ve škole.");
add("la stampante","tiskárna","Škola a práce","A2","la stam-pan-te","La stampante non funziona.","Tiskárna nefunguje.");
add("il foglio","list papíru","Škola a práce","A1","il fol-jo","Prendo un foglio.","Vezmu si list papíru.");
add("il compito","domácí úkol","Škola a práce","A1","il kom-pi-to","Faccio i compiti.","Dělám domácí úkoly.");
add("il voto","hodnocení/známka","Škola a práce","A1","il vo-to","Ho preso un bel voto.","Dostal jsem dobrou známku.");
add("l'esame","zkouška","Škola a práce","A1","le-za-me","Ho l'esame domani.","Mám zítra zkoušku.");
add("il test","test","Škola a práce","A1","il test","Ho un test di matematica.","Mám test z matematiky.");
add("la verifica","prověrka","Škola a práce","A2","la ve-ri-fi-ka","La verifica è difficile.","Prověrka je těžká.");
add("la lezione","lekce/přednáška","Škola a práce","A1","la le-tsjo-ne","La lezione dura un'ora.","Lekce trvá hodinu.");
add("il professore","profesor (muž)","Škola a práce","A1","il pro-fes-so-re","Il professore spiega bene.","Profesor vysvětluje dobře.");
add("la professoressa","profesorka","Škola a práce","A1","la pro-fes-so-res-sa","La professoressa è severa.","Profesorka je přísná.");
add("lo studente","student (muž)","Škola a práce","A1","lo stu-den-te","Lo studente studia molto.","Student hodně studuje.");
add("la studentessa","studentka","Škola a práce","A1","la stu-den-tes-sa","La studentessa è brava.","Studentka je šikovná.");
add("il rettore","rektor","Škola a práce","A2","il ret-to-re","Il rettore dell'università.","Rektor univerzity.");
add("la segreteria","sekretariát","Škola a práce","A2","la se-gre-te-ri-a","Vado in segreteria.","Jdu na sekretariát.");
add("il registro","třídní kniha","Škola a práce","A2","il re-dʒis-tro","Il professore firma il registro.","Profesor podepisuje třídní knihu.");
add("la pagella","vysvědčení","Škola a práce","A2","la pa-dʒel-la","Ricevo la pagella.","Dostávám vysvědčení.");
add("la borsa di studio","stipendium","Škola a práce","A2","la bor-sa di stu-djo","Ho una borsa di studio.","Mám stipendium.");
add("l'università","univerzita","Škola a práce","A1","lu-ni-ver-si-ta","Studio all'università.","Studuji na univerzitě.");
add("la facoltà","fakulta","Škola a práce","A2","la fa-kol-ta","La facoltà di medicina.","Lékařská fakulta.");
add("il corso","kurz","Škola a práce","A1","il kor-so","Seguo un corso di italiano.","Navštěvuji kurz italštiny.");
add("il diploma","diplom","Škola a práce","A2","il di-plo-ma","Ho preso il diploma.","Získal jsem diplom.");
add("la laurea","akademický titul","Škola a práce","A2","la lau-re-a","Ho la laurea in legge.","Mám titul z práva.");
add("l'ufficio","kancelář","Škola a práce","A1","luf-fi-cho","Lavoro in ufficio.","Pracuji v kanceláři.");
add("il collega","kolega","Škola a práce","A1","il kol-le-ga","Il mio collega è gentile.","Můj kolega je milý.");
add("il capo","šéf","Škola a práce","A1","il ka-po","Il mio capo è esigente.","Můj šéf je náročný.");
add("la riunione","schůze/porada","Škola a práce","A2","la ri-u-njo-ne","Ho una riunione alle dieci.","Mám poradu v deset.");
add("la riunione d'affari","obchodní schůzka","Škola a práce","A2","la ri-u-njo-ne daf-fa-ri","Una riunione d'affari importante.","Důležitá obchodní schůzka.");
add("il contratto","smlouva","Škola a práce","A2","il kon-trat-to","Firmo il contratto.","Podepisuji smlouvu.");
add("lo stipendio","plat","Škola a práce","A2","lo sti-pen-djo","Lo stipendio mensile.","Měsíční plat.");
add("il salario","mzda","Škola a práce","A2","il sa-la-rjo","Un salario minimo.","Minimální mzda.");
add("le ferie","dovolená","Škola a práce","A2","le fe-rje","Prendo le ferie in agosto.","Beru dovolenou v srpnu.");
add("il congedo","pracovní volno","Škola a práce","A2","il kon-dʒe-do","Il congedo di maternità.","Mateřská dovolená.");
add("il licenziamento","propuštění","Škola a práce","A2","il li-chen-tsja-men-to","Ho ricevuto il licenziamento.","Dostal jsem výpověď.");
add("disoccupato","nezaměstnaný","Škola a práce","A2","di-zok-ku-pa-to","Sono disoccupato da tre mesi.","Jsem nezaměstnaný tři měsíce.");
add("il curriculum","životopis","Škola a práce","A2","il ku-ri-ku-lum","Mando il curriculum.","Posílám životopis.");
add("il colloquio","pohovor","Škola a práce","A2","il kol-lo-kwjo","Ho un colloquio di lavoro.","Mám pracovní pohovor.");
add("l'azienda","firma/podnik","Škola a práce","A2","la-dzjen-da","Lavoro in un'azienda grande.","Pracuji ve velké firmě.");
add("il dipendente","zaměstnanec","Škola a práce","A2","il di-pen-den-te","I dipendenti dell'azienda.","Zaměstnanci firmy.");
add("il datore di lavoro","zaměstnavatel","Škola a práce","A2","il da-to-re di la-vo-ro","Il mio datore di lavoro è giusto.","Můj zaměstnavatel je spravedlivý.");
add("fare lo straordinario","přesčasovat","Škola a práce","A2","fa-re lo stra-or-di-na-rjo","Faccio spesso lo straordinario.","Často přesčasuji.");
add("lavorare da casa","pracovat z domu","Škola a práce","A2","la-vo-ra-re da ka-za","Lavoro da casa oggi.","Dnes pracuji z domu.");
add("la videoconferenza","videokonference","Škola a práce","A2","la vi-de-o-kon-fe-ren-dza","Una videoconferenza con il team.","Videokonference s týmem.");
add("il tirocinio","stáž","Škola a práce","A2","il ti-ro-chi-njo","Faccio un tirocinio in azienda.","Dělám stáž ve firmě.");
add("il sindacato","odborová organizace","Škola a práce","B1","il sin-da-ka-to","Sono membro del sindacato.","Jsem člen odborů.");
add("il bilancio","bilance/rozpočet","Škola a práce","A2","il bi-lan-cho","Il bilancio annuale.","Roční bilance.");
add("la produzione","výroba","Škola a práce","A2","la pro-du-tsjo-ne","La produzione industriale.","Průmyslová výroba.");
add("l'impresa","podnik","Škola a práce","A2","lim-pre-za","Una piccola impresa.","Malý podnik.");
add("il progetto","projekt","Škola a práce","A2","il pro-dʒet-to","Lavoro a un progetto nuovo.","Pracuji na novém projektu.");
add("il budget","rozpočet","Škola a práce","A2","il bad-dʒet","Il budget del progetto.","Rozpočet projektu.");
add("la scadenza","termín/deadline","Škola a práce","A2","la ska-den-dza","La scadenza è domani.","Deadline je zítra.");
add("il cliente","zákazník","Škola a práce","A2","il klien-te","Il cliente ha chiamato.","Zákazník volal.");
add("la consegna","dodávka/odevzdání","Škola a práce","A2","la kon-se-nja","La consegna del progetto.","Odevzdání projektu.");
add("il settore","sektor/odvětví","Škola a práce","A2","il set-to-re","Il settore privato.","Soukromý sektor.");
add("il mercato","trh","Škola a práce","A2","il mer-ka-to","Il mercato del lavoro.","Trh práce.");
add("la crisi economica","hospodářská krize","Škola a práce","B1","la kri-zi e-ko-no-mi-ka","La crisi economica globale.","Globální hospodářská krize.");
add("il tasso di disoccupazione","míra nezaměstnanosti","Škola a práce","B1","il tas-so di di-zok-ku-pa-tsjo-ne","Il tasso di disoccupazione è alto.","Míra nezaměstnanosti je vysoká.");

// ═══════════════════════════════════════════════════════
// MĚSTO A DOPRAVA (+76) — cíl: 100
// ═══════════════════════════════════════════════════════
add("la città","město","Město a doprava","A1","la chit-ta","Abito in città.","Bydlím ve městě.");
add("il centro","centrum","Město a doprava","A1","il chen-tro","Il centro della città.","Centrum města.");
add("il quartiere","čtvrť","Město a doprava","A1","il kwar-tje-re","Il quartiere storico.","Historická čtvrť.");
add("il comune","obec/magistrát","Město a doprava","A2","il ko-mu-ne","Il comune di Milano.","Milánský magistrát.");
add("la piazza","náměstí","Město a doprava","A1","la pjat-tsa","La piazza principale.","Hlavní náměstí.");
add("la via","ulice","Město a doprava","A1","la vi-a","La via principale.","Hlavní ulice.");
add("il viale","třída/bulvár","Město a doprava","A1","il vja-le","Un viale alberato.","Stromová třída.");
add("il vicolo","ulička","Město a doprava","A2","il vi-ko-lo","Un vicolo stretto.","Úzká ulička.");
add("il marciapiede","chodník","Město a doprava","A1","il mar-cha-pje-de","Cammino sul marciapiede.","Chodím po chodníku.");
add("il semaforo","semafor","Město a doprava","A1","il se-ma-fo-ro","Il semaforo è rosso.","Semafor je červený.");
add("il passaggio pedonale","přechod pro chodce","Město a doprava","A1","il pas-sad-dʒo pe-do-na-le","Attraversa al passaggio pedonale.","Přejdi na přechodu pro chodce.");
add("il parcheggio","parkoviště","Město a doprava","A1","il par-ked-dʒo","Cerco un parcheggio.","Hledám parkoviště.");
add("il garage","garáž","Město a doprava","A1","il ga-radʒ","L'auto è in garage.","Auto je v garáži.");
add("la rotonda","kruhový objezd","Město a doprava","A2","la ro-ton-da","Alla rotonda, gira a destra.","Na kruhovém objezdu zatoč doprava.");
add("il tunnel","tunel","Město a doprava","A2","il tun-nel","Il tunnel autostradale.","Dálniční tunel.");
add("il ponte","most","Město a doprava","A1","il pon-te","Il ponte sul fiume.","Most přes řeku.");
add("la fermata","zastávka","Město a doprava","A1","la fer-ma-ta","La fermata dell'autobus.","Autobusová zastávka.");
add("la stazione","nádraží","Město a doprava","A1","la sta-tsjo-ne","La stazione centrale.","Hlavní nádraží.");
add("l'aeroporto","letiště","Město a doprava","A1","la-e-ro-por-to","L'aeroporto di Roma.","Letiště v Římě.");
add("il porto","přístav","Město a doprava","A1","il por-to","Il porto di Genova.","Přístav v Janově.");
add("l'autostrada","dálnice","Město a doprava","A1","lau-to-stra-da","Prendo l'autostrada.","Jedu po dálnici.");
add("la strada statale","státní silnice","Město a doprava","A2","la stra-da sta-ta-le","Una strada statale trafficata.","Rušná státní silnice.");
add("il casello","dálniční brána","Město a doprava","A2","il ka-zel-lo","Pago al casello.","Platím na dálniční bráně.");
add("il pedaggio","mýtné","Město a doprava","A2","il pe-dad-dʒo","Il pedaggio autostradale.","Dálniční mýtné.");
add("la mappa","mapa","Město a doprava","A1","la map-pa","Guardo la mappa.","Dívám se na mapu.");
add("il navigatore","navigace/GPS","Město a doprava","A2","il na-vi-ga-to-re","Uso il navigatore.","Používám navigaci.");
add("il tragitto","trasa/cesta","Město a doprava","A2","il tra-dʒit-to","Quale tragitto prendi?","Jakou trasu jdeš?");
add("la corsia","jízdní pruh","Město a doprava","A2","la kor-sja","La corsia di destra.","Pravý jízdní pruh.");
add("il sorpasso","předjetí","Město a doprava","A2","il sor-pas-so","Il sorpasso è vietato.","Předjíždění je zakázáno.");
add("la multa","pokuta","Město a doprava","A2","la mul-ta","Ho preso una multa.","Dostal jsem pokutu.");
add("la patente","řidičský průkaz","Město a doprava","A1","la pa-ten-te","Ho la patente di guida.","Mám řidičský průkaz.");
add("il veicolo","vozidlo","Město a doprava","A2","il ve-i-ko-lo","Un veicolo pesante.","Těžké vozidlo.");
add("la moto","motorka","Město a doprava","A1","la mo-to","Vado in moto.","Jedu na motorce.");
add("il camion","nákladní auto","Město a doprava","A1","il ka-mjon","Il camion è grande.","Nákladní auto je velké.");
add("il furgone","dodávka","Město a doprava","A2","il fur-go-ne","Il furgone della pizzeria.","Dodávka pizzerie.");
add("il taxi","taxi","Město a doprava","A1","il tak-si","Prendo un taxi.","Beru taxi.");
add("la metro","metro","Město a doprava","A1","la me-tro","Vado in metro.","Jedu metrem.");
add("il tram","tramvaj","Město a doprava","A1","il tram","Il tram numero cinque.","Tramvaj číslo pět.");
add("il filobus","trolejbus","Město a doprava","A2","il fi-lo-bus","Il filobus elettrico.","Elektrický trolejbus.");
add("la funicolare","lanovka","Město a doprava","A2","la fu-ni-ko-la-re","La funicolare al Vesuvio.","Lanovka na Vesuv.");
add("la nave","loď","Město a doprava","A1","la na-ve","Prendo la nave per la Sardegna.","Jedu lodí na Sardínii.");
add("il traghetto","trajekt","Město a doprava","A1","il tra-get-to","Il traghetto per l'isola.","Trajekt na ostrov.");
add("l'aliscafo","hydroglissér","Město a doprava","A2","la-lis-ka-fo","L'aliscafo per Capri.","Hydroglissér na Capri.");
add("il treno ad alta velocità","vysokorychlostní vlak","Město a doprava","A2","il tre-no ad al-ta ve-lo-chi-ta","Il treno ad alta velocità.","Vysokorychlostní vlak.");
add("l'Intercity","mezistátní vlak","Město a doprava","A2","lin-ter-si-ti","L'Intercity per Roma.","Mezistátní vlak do Říma.");
add("il convoglio","vlakový spoj","Město a doprava","B1","il kon-vol-jo","Il convoglio notturno.","Noční vlakový spoj.");
add("i binari","koleje","Město a doprava","A2","i bi-na-ri","Il treno sui binari.","Vlak na kolejích.");
add("la banchina","nástupník","Město a doprava","A2","la ban-ki-na","La banchina numero tre.","Nástupník číslo tři.");
add("la biglietteria","pokladna","Město a doprava","A1","la bil-jet-te-ri-a","La biglietteria della stazione.","Pokladna nádraží.");
add("il check-in","odbavení","Město a doprava","A2","il chek-in","Il check-in all'aeroporto.","Odbavení na letišti.");
add("il gate","odletová brána","Město a doprava","A2","il geit","Il gate di imbarco.","Odletová brána.");
add("il volo","let/letadlo","Město a doprava","A1","il vo-lo","Il volo per Londra.","Let do Londýna.");
add("la turbulenza","turbulence","Město a doprava","A2","la tur-bu-len-dza","C'è turbulenza.","Je turbulence.");
add("l'atterraggio","přistání","Město a doprava","A2","lat-ter-rad-dʒo","L'atterraggio è morbido.","Přistání je měkké.");
add("il decollo","vzlet","Město a doprava","A2","il de-kol-lo","Il decollo alle sei.","Vzlet v šest.");
add("la dogana","celnice","Město a doprava","A2","la do-ga-na","Passo la dogana.","Procházím celnicí.");
add("il controllo passaporti","pasová kontrola","Město a doprava","A2","il kon-trol-lo pas-sa-por-ti","Il controllo passaporti è lungo.","Pasová kontrola je dlouhá.");
add("l'emigrante","emigrant","Město a doprava","A2","le-mi-gran-te","Un emigrante italiano.","Italský emigrant.");
add("la distanza","vzdálenost","Město a doprava","A1","la dis-tan-dza","La distanza è di cento km.","Vzdálenost je sto km.");
add("il carburante","palivo","Město a doprava","A2","il kar-bu-ran-te","Il carburante costa caro.","Palivo je drahé.");
add("il benzinaio","čerpací stanice","Město a doprava","A1","il ben-dzi-na-jo","Mi fermo al benzinaio.","Zastavím u čerpací stanice.");
add("la benzina","benzín","Město a doprava","A1","la ben-dzi-na","Faccio benzina.","Tankovám benzín.");
add("il diesel","nafta","Město a doprava","A2","il die-sel","Un'auto diesel.","Naftové auto.");
add("il meccanico","mechanik","Město a doprava","A2","il mek-ka-ni-ko","Il meccanico ripara la macchina.","Mechanik opravuje auto.");
add("l'officina","autoservis","Město a doprava","A2","lof-fi-chi-na","Porto la macchina in officina.","Vezmu auto do servisu.");
add("la gomma a terra","defekt","Město a doprava","A2","la gom-ma a ter-ra","Ho una gomma a terra.","Mám defekt.");
add("il carro attrezzi","odtahový vůz","Město a doprava","A2","il kar-ro at-tret-tsi","Chiamo il carro attrezzi.","Zavolám odtahový vůz.");
add("il segnale stradale","dopravní značka","Město a doprava","A2","il se-nja-le stra-da-le","Rispetta i segnali stradali.","Respektuj dopravní značky.");
add("il divieto di sosta","zákaz stání","Město a doprava","A2","il di-vje-to di sos-ta","C'è il divieto di sosta.","Je zde zákaz stání.");
add("la zona a traffico limitato","zóna s omezeným provozem","Město a doprava","A2","la dzo-na a traf-fi-ko li-mi-ta-to","Siamo in ZTL.","Jsme v zóně s omezeným provozem.");
add("la pista ciclabile","cyklostezka","Město a doprava","A2","la pis-ta chi-kla-bi-le","Vado in bici sulla pista.","Jedu na kole po cyklostezce.");
add("il monopattino","koloběžka","Město a doprava","A2","il mo-no-pat-ti-no","Il monopattino elettrico.","Elektrická koloběžka.");
add("condividere","sdílet","Město a doprava","A2","kon-di-vi-de-re","Condividiamo la macchina.","Sdílíme auto.");
add("il car sharing","sdílené auto","Město a doprava","A2","il kar she-rin","Uso il car sharing.","Používám sdílené auto.");

// ═══════════════════════════════════════════════════════
// ČAS A DNY (+63) — cíl: 100
// ═══════════════════════════════════════════════════════
add("il secondo","sekunda","Čas a dny","A1","il se-kon-do","Aspetta un secondo.","Počkej sekundu.");
add("il minuto","minuta","Čas a dny","A1","il mi-nu-to","Ci vuole un minuto.","Trvá to minutu.");
add("l'ora","hodina","Čas a dny","A1","lo-ra","Un'ora di lezione.","Hodina výuky.");
add("la mattina","ráno","Čas a dny","A1","la mat-ti-na","La mattina presto.","Brzy ráno.");
add("il pomeriggio","odpoledne","Čas a dny","A1","il po-me-rid-dʒo","Nel pomeriggio.","Odpoledne.");
add("la sera","večer","Čas a dny","A1","la se-ra","Buona sera!","Dobrý večer!");
add("la notte","noc","Čas a dny","A1","la not-te","Di notte fa freddo.","V noci je chladno.");
add("il mezzogiorno","poledne","Čas a dny","A1","il med-dzo-djor-no","A mezzogiorno mangio.","V poledne jím.");
add("la mezzanotte","půlnoc","Čas a dny","A1","la med-dza-not-te","A mezzanotte festeggiamo.","O půlnoci slavíme.");
add("il passato","minulost","Čas a dny","A2","il pas-sa-to","Nel passato era diverso.","V minulosti bylo jinak.");
add("il futuro","budoucnost","Čas a dny","A2","il fu-tu-ro","Il futuro è incerto.","Budoucnost je nejistá.");
add("il presente","přítomnost","Čas a dny","A2","il pre-zen-te","Vivo nel presente.","Žiji v přítomnosti.");
add("fa molto tempo","před dávnou dobou","Čas a dny","A2","fa mol-to tem-po","Fa molto tempo non ci siamo visti.","Dlouho jsme se neviděli.");
add("recentemente","nedávno","Čas a dny","A2","re-chen-te-men-te","L'ho fatto recentemente.","Udělal jsem to nedávno.");
add("prossimamente","brzy/v blízké době","Čas a dny","A2","pros-si-ma-men-te","Prossimamente ci vediamo.","Brzy se uvidíme.");
add("abitualmente","obvykle","Čas a dny","A2","a-bi-twal-men-te","Abitualmente mi sveglio presto.","Obvykle vstávám brzy.");
add("raramente","zřídka","Čas a dny","A2","ra-ra-men-te","Raramente vado al cinema.","Zřídka chodím do kina.");
add("talvolta","někdy","Čas a dny","A2","tal-vol-ta","Talvolta mi annoio.","Někdy se nudím.");
add("di tanto in tanto","čas od času","Čas a dny","A2","di tan-to in tan-to","Di tanto in tanto lo vedo.","Čas od času ho vídám.");
add("all'alba","za úsvitu","Čas a dny","A2","al-al-ba","Mi sveglio all'alba.","Vstávám za úsvitu.");
add("al tramonto","při západu slunce","Čas a dny","A2","al tra-mon-to","Una passeggiata al tramonto.","Procházka při západu slunce.");
add("il decennio","desetiletí","Čas a dny","A2","il de-chen-njo","L'ultimo decennio.","Poslední desetiletí.");
add("il secolo","století","Čas a dny","A2","il se-ko-lo","Il ventunesimo secolo.","21. století.");
add("il millennio","tisíciletí","Čas a dny","A2","il mil-len-njo","Il terzo millennio.","Třetí tisíciletí.");
add("il biennio","dvouletí","Čas a dny","A2","il bjen-njo","Un biennio scolastico.","Dvouletý školní cyklus.");
add("il trimestre","čtvrtletí","Čas a dny","A2","il tri-mes-tre","Il primo trimestre.","První čtvrtletí.");
add("il semestre","semestr/pololetí","Čas a dny","A2","il se-mes-tre","Il secondo semestre.","Druhý semestr.");
add("il calendario","kalendář","Čas a dny","A1","il ka-len-da-rjo","Guardo il calendario.","Dívám se do kalendáře.");
add("la data","datum","Čas a dny","A1","la da-ta","Che data è oggi?","Jaké je dnes datum?");
add("l'anno scorso","loňský rok","Čas a dny","A1","lan-no skor-so","L'anno scorso ero a Parigi.","Loňský rok jsem byl v Paříži.");
add("l'anno prossimo","příští rok","Čas a dny","A1","lan-no pros-si-mo","L'anno prossimo andrò in Italia.","Příští rok pojedu do Itálie.");
add("in anticipo","předčasně/brzy","Čas a dny","A2","in an-ti-chi-po","Sono arrivato in anticipo.","Přišel jsem předčasně.");
add("in ritardo","se zpožděním","Čas a dny","A2","in ri-tar-do","Il treno è in ritardo.","Vlak má zpoždění.");
add("puntuale","dochvilný","Čas a dny","A2","pun-twa-le","Sono sempre puntuale.","Jsem vždy dochvilný.");
add("l'orologio","hodiny/hodinky","Čas a dny","A1","lo-ro-lo-dʒo","Il mio orologio segna le tre.","Mé hodinky ukazují tři.");
add("il fuso orario","časové pásmo","Čas a dny","A2","il fu-zo o-ra-rjo","Il fuso orario di Roma.","Časové pásmo Říma.");
add("il quarto d'ora","čtvrt hodiny","Čas a dny","A1","il kwar-to do-ra","Aspetto un quarto d'ora.","Čekám čtvrt hodiny.");
add("la mezz'ora","půl hodiny","Čas a dny","A1","la med-dzo-ra","Tra mezz'ora arrivo.","Za půl hodiny přijdu.");
add("il fine settimana","víkend","Čas a dny","A1","il fi-ne set-ti-ma-na","Il fine settimana vado fuori.","O víkendu jdu ven.");
add("il ferragosto","svátek v srpnu","Čas a dny","A2","il fer-ra-gos-to","Chiude per ferragosto.","Zavřeno kvůli srpnovým svátkům.");
add("la vigilia","předvečer/Štědrý den","Čas a dny","A2","la vi-dʒi-lja","La vigilia di Natale.","Štědrý večer.");
add("il capodanno","Nový rok","Čas a dny","A1","il ka-po-dan-no","Buon Capodanno!","Šťastný nový rok!");
add("la Pasqua","Velikonoce","Čas a dny","A1","la pas-kwa","Buona Pasqua!","Veselé Velikonoce!");
add("il Natale","Vánoce","Čas a dny","A1","il na-ta-le","Buon Natale!","Veselé Vánoce!");
add("il compleanno","narozeniny","Čas a dny","A1","il kom-ple-an-no","Buon compleanno!","Vše nejlepší k narozeninám!");
add("l'anniversario","výročí","Čas a dny","A2","lan-ni-ver-sa-rjo","Il nostro anniversario.","Naše výročí.");
add("il Capodanno cinese","čínský nový rok","Čas a dny","A2","il ka-po-dan-no chi-ne-ze","Il Capodanno cinese.","Čínský nový rok.");
add("il giorno feriale","pracovní den","Čas a dny","A2","il djor-no fe-rja-le","Un giorno feriale.","Pracovní den.");
add("il giorno festivo","svátek","Čas a dny","A2","il djor-no fes-ti-vo","Un giorno festivo.","Sváteční den.");
add("oggi","dnes","Čas a dny","A1","od-dʒi","Oggi è lunedì.","Dnes je pondělí.");
add("ieri","včera","Čas a dny","A1","je-ri","Ieri sono uscito.","Včera jsem šel ven.");
add("domani","zítra","Čas a dny","A1","do-ma-ni","Domani parto.","Zítra odjíždím.");
add("l'altro ieri","předevčírem","Čas a dny","A2","lal-tro je-ri","L'altro ieri l'ho visto.","Předevčírem jsem ho viděl.");
add("dopodomani","pozítří","Čas a dny","A2","do-po-do-ma-ni","Torno dopodomani.","Vrátím se pozítří.");
add("questa settimana","tento týden","Čas a dny","A1","kwes-ta set-ti-ma-na","Questa settimana sono occupato.","Tento týden jsem zaneprázdněn.");
add("la prossima settimana","příští týden","Čas a dny","A1","la pros-si-ma set-ti-ma-na","La prossima settimana ci vediamo.","Příští týden se uvidíme.");
add("questo mese","tento měsíc","Čas a dny","A1","kwes-to me-ze","Questo mese è agosto.","Tento měsíc je srpen.");
add("il mese scorso","minulý měsíc","Čas a dny","A1","il me-ze skor-so","Il mese scorso ero a Napoli.","Minulý měsíc jsem byl v Neapoli.");
add("quest'anno","letos","Čas a dny","A1","kwes-tan-no","Quest'anno vado in vacanza.","Letos jdu na dovolenou.");
add("ogni giorno","každý den","Čas a dny","A1","on-ji djor-no","Studio ogni giorno.","Studuji každý den.");
add("ogni settimana","každý týden","Čas a dny","A1","on-ji set-ti-ma-na","Lo faccio ogni settimana.","Dělám to každý týden.");
add("una volta al mese","jednou za měsíc","Čas a dny","A2","u-na vol-ta al me-ze","Lo vedo una volta al mese.","Vidím ho jednou za měsíc.");
add("due volte alla settimana","dvakrát týdně","Čas a dny","A2","du-e vol-te al-la set-ti-ma-na","Vado in palestra due volte alla settimana.","Chodím do posilovny dvakrát týdně.");

// ═══════════════════════════════════════════════════════
// VOLNÝ ČAS A SPORT (+68) — cíl: 100
// ═══════════════════════════════════════════════════════
add("il calcio","fotbal","Volný čas a sport","A1","il kal-cho","Gioco a calcio.","Hraji fotbal.");
add("il basket","basketbal","Volný čas a sport","A1","il bas-ket","Gioco a basket.","Hraji basketbal.");
add("il nuoto","plavání","Volný čas a sport","A1","il nwo-to","Mi piace il nuoto.","Rád plavám.");
add("la corsa","běh","Volný čas a sport","A1","la kor-sa","Faccio una corsa.","Jdu běhat.");
add("la palestra","posilovna/tělocvična","Volný čas a sport","A1","la pa-les-tra","Vado in palestra.","Jdu do posilovny.");
add("l'allenamento","trénink","Volný čas a sport","A1","lal-le-na-men-to","L'allenamento è duro.","Trénink je tvrdý.");
add("l'allenatore","trenér","Volný čas a sport","A1","lal-le-na-to-re","Il mio allenatore è bravo.","Můj trenér je dobrý.");
add("la squadra","tým","Volný čas a sport","A1","la skwa-dra","La nostra squadra ha vinto.","Náš tým vyhrál.");
add("il campionato","mistrovství/liga","Volný čas a sport","A2","il kam-pjo-na-to","Il campionato italiano.","Italská liga.");
add("la partita","zápas","Volný čas a sport","A1","la par-ti-ta","La partita è stasera.","Zápas je dnes večer.");
add("il torneo","turnaj","Volný čas a sport","A2","il tor-ne-o","Un torneo di tennis.","Tenisový turnaj.");
add("la finale","finále","Volný čas a sport","A2","la fi-na-le","La finale del campionato.","Finále mistrovství.");
add("il campione","šampion","Volný čas a sport","A2","il kam-pjo-ne","Il campione del mondo.","Mistr světa.");
add("la medaglia","medaile","Volný čas a sport","A1","la me-dal-ja","Una medaglia d'oro.","Zlatá medaile.");
add("il podio","stupně vítězů","Volný čas a sport","A2","il po-djo","Salire sul podio.","Vystoupit na stupně vítězů.");
add("il record","rekord","Volný čas a sport","A1","il re-kor","Un nuovo record mondiale.","Nový světový rekord.");
add("la pallavolo","volejbal","Volný čas a sport","A1","la pal-la-vo-lo","La pallavolo è divertente.","Volejbal je zábavný.");
add("il tennis","tenis","Volný čas a sport","A1","il ten-nis","Gioco a tennis.","Hraji tenis.");
add("il golf","golf","Volný čas a sport","A2","il golf","Gioco a golf.","Hraji golf.");
add("il ciclismo","cyklistika","Volný čas a sport","A2","il chi-klis-mo","Il ciclismo è il mio sport.","Cyklistika je můj sport.");
add("lo sci","lyžování","Volný čas a sport","A1","lo shi","Vado a sciare.","Jdu lyžovat.");
add("il pattinaggio","bruslení","Volný čas a sport","A2","il pat-ti-nad-dʒo","Il pattinaggio sul ghiaccio.","Bruslení na ledě.");
add("l'equitazione","jezdectví","Volný čas a sport","A2","le-kwi-ta-tsjo-ne","Faccio equitazione.","Věnuji se jezdectví.");
add("il tiro con l'arco","lukostřelba","Volný čas a sport","A2","il ti-ro kon lar-ko","Il tiro con l'arco.","Lukostřelba.");
add("la boxe","box","Volný čas a sport","A2","la boks","Pratica la boxe.","Cvičí box.");
add("le arti marziali","bojová umění","Volný čas a sport","A2","le ar-ti mar-tsja-li","Le arti marziali asiatiche.","Asijská bojová umění.");
add("il karate","karate","Volný čas a sport","A1","il ka-ra-te","Faccio karate.","Cvičím karate.");
add("il judo","judo","Volný čas a sport","A2","il ju-do","Pratica il judo.","Cvičí judo.");
add("lo yoga","jóga","Volný čas a sport","A1","lo jo-ga","Faccio yoga.","Cvičím jógu.");
add("la meditazione","meditace","Volný čas a sport","A2","la me-di-ta-tsjo-ne","La meditazione quotidiana.","Každodenní meditace.");
add("il fitness","fitness","Volný čas a sport","A1","il fit-nes","Vado a fare fitness.","Jdu na fitness.");
add("l'aerobica","aerobik","Volný čas a sport","A2","la-e-ro-bi-ka","Faccio aerobica.","Cvičím aerobik.");
add("il pilates","pilates","Volný čas a sport","A2","il pi-la-tes","Faccio pilates.","Cvičím pilates.");
add("la danza","tanec","Volný čas a sport","A1","la dan-dza","Studio danza.","Studuji tanec.");
add("il ballo","ples/tanec","Volný čas a sport","A1","il bal-lo","Vado a ballare.","Jdu tančit.");
add("la salsa","salsa","Volný čas a sport","A2","la sal-sa","Ballo la salsa.","Tančím salsu.");
add("il tango","tango","Volný čas a sport","A2","il tan-go","Il tango argentino.","Argentinské tango.");
add("il cinema","kino","Volný čas a sport","A1","il chi-ne-ma","Andiamo al cinema.","Pojďme do kina.");
add("il teatro","divadlo","Volný čas a sport","A1","il te-a-tro","Lo spettacolo a teatro.","Představení v divadle.");
add("la mostra","výstava","Volný čas a sport","A2","la mos-tra","Una mostra d'arte.","Umělecká výstava.");
add("il concerto","koncert","Volný čas a sport","A1","il kon-cher-to","Vado al concerto stasera.","Dnes večer jdu na koncert.");
add("il festival","festival","Volný čas a sport","A1","il fes-ti-val","Il festival musicale.","Hudební festival.");
add("la fotografia","fotografie","Volný čas a sport","A1","la fo-to-gra-fi-a","Mi piace la fotografia.","Mám rád fotografii.");
add("la pittura","malířství","Volný čas a sport","A2","la pit-tu-ra","Studio pittura.","Studuji malířství.");
add("il giardinaggio","zahradničení","Volný čas a sport","A2","il dʒar-di-nad-dʒo","Mi piace il giardinaggio.","Rád zahradničím.");
add("il bricolage","kutilství","Volný čas a sport","A2","il bri-ko-ladʒ","Faccio bricolage.","Kutím.");
add("la pesca","rybaření","Volný čas a sport","A1","la pes-ka","Vado a pesca.","Jdu na ryby.");
add("la caccia","lov","Volný čas a sport","A2","la kat-cha","La caccia è vietata.","Lov je zakázán.");
add("l'escursione","výlet","Volný čas a sport","A2","les-kur-sjo-ne","Una bella escursione.","Krásný výlet.");
add("il campeggio","kempování","Volný čas a sport","A1","il kam-ped-dʒo","Andiamo in campeggio.","Jdeme kempovat.");
add("la cucina","vaření/kuchyně","Volný čas a sport","A1","la ku-chi-na","Mi piace la cucina italiana.","Mám rád italské vaření.");
add("la lettura","čtení","Volný čas a sport","A1","la let-tu-ra","La lettura è rilassante.","Čtení je relaxační.");
add("il videogioco","videohry","Volný čas a sport","A1","il vi-de-o-dʒo-ko","Gioco ai videogiochi.","Hraji videohry.");
add("il puzzle","puzzle","Volný čas a sport","A1","il paz-zel","Faccio un puzzle.","Skládám puzzle.");
add("gli scacchi","šachy","Volný čas a sport","A2","gli skak-ki","Gioco a scacchi.","Hraji šachy.");
add("le carte","karty","Volný čas a sport","A1","le kar-te","Giochiamo a carte.","Hrajeme karty.");
add("il volontariato","dobrovolnictví","Volný čas a sport","A2","il vo-lon-ta-rja-to","Faccio volontariato.","Dělám dobrovolnictví.");
add("il riposo","odpočinek","Volný čas a sport","A1","il ri-po-zo","Ho bisogno di riposo.","Potřebuji odpočinek.");
add("il relax","relaxace","Volný čas a sport","A1","il re-laks","Un po' di relax.","Trochu relaxace.");
add("il divertimento","zábava","Volný čas a sport","A1","il di-ver-ti-men-to","Buon divertimento!","Dobrou zábavu!");
add("la passione","vášeň","Volný čas a sport","A2","la pas-sjo-ne","La mia passione è la musica.","Mou vášní je hudba.");
add("l'hobby","koníček","Volný čas a sport","A1","lob-bi","Il mio hobby è dipingere.","Mým koníčkem je malování.");
add("lo sport estremo","extrémní sport","Volný čas a sport","A2","lo sport es-tre-mo","Pratica sport estremi.","Provozuje extrémní sporty.");
add("il paracadutismo","parašutismus","Volný čas a sport","A2","il pa-ra-ka-du-tis-mo","Il paracadutismo è emozionante.","Parašutismus je vzrušující.");
add("l'arrampicata","horolezectví","Volný čas a sport","A2","lar-ram-pi-ka-ta","L'arrampicata sportiva.","Sportovní lezení.");
add("il surf","surfování","Volný čas a sport","A2","il serf","Faccio surf.","Surfuji.");

// ═══════════════════════════════════════════════════════
// EMOCE A VLASTNOSTI (+62) — cíl: 100
// ═══════════════════════════════════════════════════════
add("la gioia","radost","Emoce a vlastnosti","A1","la dʒo-ja","Provo una grande gioia.","Prožívám velkou radost.");
add("la tristezza","smutek","Emoce a vlastnosti","A1","la tris-tet-tsa","La tristezza è normale.","Smutek je normální.");
add("la rabbia","vztek","Emoce a vlastnosti","A1","la rab-bja","Provo rabbia.","Prožívám vztek.");
add("la paura","strach","Emoce a vlastnosti","A1","la pa-u-ra","Ho paura del buio.","Bojím se tmy.");
add("la sorpresa","překvapení","Emoce a vlastnosti","A1","la sor-pre-za","Che bella sorpresa!","Jaké krásné překvapení!");
add("il disgusto","znechucení","Emoce a vlastnosti","A2","il dis-gus-to","Sento disgusto.","Cítím znechucení.");
add("l'entusiasmo","nadšení","Emoce a vlastnosti","A2","len-tu-zjaz-mo","Il suo entusiasmo è contagioso.","Jeho nadšení je nakažlivé.");
add("la delusione","zklamání","Emoce a vlastnosti","A2","la de-lu-zjo-ne","Sento una delusione.","Cítím zklamání.");
add("l'orgoglio","hrdost","Emoce a vlastnosti","A2","lor-gol-jo","Provo orgoglio.","Prožívám hrdost.");
add("la vergogna","stud","Emoce a vlastnosti","A2","la ver-gon-ja","Mi sento in vergogna.","Stydím se.");
add("la gelosia","žárlivost","Emoce a vlastnosti","A2","la dʒe-lo-zi-a","La gelosia fa male.","Žárlivost bolí.");
add("l'invidia","závist","Emoce a vlastnosti","A2","lin-vi-dja","L'invidia è brutta.","Závist je škaredá.");
add("la speranza","naděje","Emoce a vlastnosti","A2","la spe-ran-dza","Ho speranza nel futuro.","Mám naději v budoucnost.");
add("la nostalgia","nostalgie","Emoce a vlastnosti","A2","la nos-tal-dʒa","Sento nostalgia.","Cítím nostalgii.");
add("l'ansia","úzkost","Emoce a vlastnosti","A2","lan-sja","L'ansia mi blocca.","Úzkost mě blokuje.");
add("la calma","klid","Emoce a vlastnosti","A1","la kal-ma","Mantieni la calma.","Zachovej klid.");
add("il coraggio","odvaha","Emoce a vlastnosti","A2","il ko-rad-dʒo","Hai molto coraggio.","Máš velkou odvahu.");
add("la fiducia","důvěra","Emoce a vlastnosti","A2","la fi-du-cha","Ho fiducia in te.","Důvěřuji ti.");
add("la solitudine","samota","Emoce a vlastnosti","A2","la so-li-tu-di-ne","La solitudine pesa.","Samota tíží.");
add("la contentezza","spokojenost","Emoce a vlastnosti","A2","la kon-ten-tet-tsa","Sento contentezza.","Cítím spokojenost.");
add("la nostalgia di casa","stesk po domově","Emoce a vlastnosti","A2","la nos-tal-dʒa di ka-za","Ho nostalgia di casa.","Stýská se mi po domově.");
add("l'emozione","emoce","Emoce a vlastnosti","A1","le-mo-tsjo-ne","Le emozioni sono forti.","Emoce jsou silné.");
add("lo stress","stres","Emoce a vlastnosti","A1","lo stres","Ho molto stress.","Mám hodně stresu.");
add("la frustrazione","frustrace","Emoce a vlastnosti","A2","la frus-tra-tsjo-ne","Sento frustrazione.","Cítím frustraci.");
add("la soddisfazione","spokojenost/uspokojení","Emoce a vlastnosti","A2","la sod-dis-fa-tsjo-ne","Una grande soddisfazione.","Velké uspokojení.");
add("la gratitudine","vděčnost","Emoce a vlastnosti","A2","la gra-ti-tu-di-ne","Sento gratitudine.","Cítím vděčnost.");
add("la compassione","soucit","Emoce a vlastnosti","A2","la kom-pas-sjo-ne","Provo compassione.","Cítím soucit.");
add("l'empatia","empatie","Emoce a vlastnosti","B1","lem-pa-ti-a","L'empatia è importante.","Empatie je důležitá.");
add("la timidezza","nesmělost","Emoce a vlastnosti","A2","la ti-mi-det-tsa","La sua timidezza è simpatica.","Jeho nesmělost je milá.");
add("la pazienza","trpělivost","Emoce a vlastnosti","A1","la pa-tsjen-dza","Ho molta pazienza.","Mám hodně trpělivosti.");
add("l'impazienza","netrpělivost","Emoce a vlastnosti","A2","lim-pa-tsjen-dza","Sento impazienza.","Cítím netrpělivost.");
add("la generosità","štědrost","Emoce a vlastnosti","A2","la dʒe-ne-ro-zi-ta","La sua generosità è rara.","Jeho štědrost je vzácná.");
add("l'avarizia","lakomství","Emoce a vlastnosti","A2","la-va-ri-tsja","L'avarizia non è bella.","Lakomství není hezké.");
add("l'onestà","čestnost","Emoce a vlastnosti","A2","lo-nes-ta","L'onestà è fondamentale.","Čestnost je základní.");
add("la lealtà","loajalita","Emoce a vlastnosti","A2","la le-al-ta","La lealtà è importante.","Loajalita je důležitá.");
add("l'arroganza","arogance","Emoce a vlastnosti","A2","lar-ro-gan-dza","La sua arroganza dà fastidio.","Jeho arogance obtěžuje.");
add("l'umiltà","pokora","Emoce a vlastnosti","A2","lu-mil-ta","L'umiltà è una virtù.","Pokora je ctností.");
add("la curiosità","zvědavost","Emoce a vlastnosti","A2","la ku-rjo-zi-ta","La curiosità è positiva.","Zvědavost je pozitivní.");
add("la creatività","kreativita","Emoce a vlastnosti","A2","la kre-a-ti-vi-ta","La creatività non ha limiti.","Kreativita nemá hranice.");
add("la determinazione","odhodlání","Emoce a vlastnosti","A2","la de-ter-mi-na-tsjo-ne","La sua determinazione è ammirevole.","Jeho odhodlání je obdivuhodné.");
add("la saggezza","moudrost","Emoce a vlastnosti","A2","la sad-dʒet-tsa","La saggezza viene dall'esperienza.","Moudrost přichází ze zkušenosti.");
add("l'intelligenza","inteligence","Emoce a vlastnosti","A2","lin-tel-li-dʒen-dza","L'intelligenza si sviluppa.","Inteligence se rozvíjí.");
add("la sensibilità","citlivost","Emoce a vlastnosti","A2","la sen-si-bi-li-ta","La sua sensibilità è alta.","Jeho citlivost je vysoká.");
add("l'intuizione","intuice","Emoce a vlastnosti","A2","lin-tui-tsjo-ne","Segui la tua intuizione.","Sleduj svou intuici.");
add("l'ottimismo","optimismus","Emoce a vlastnosti","A2","lot-ti-mis-mo","L'ottimismo aiuta.","Optimismus pomáhá.");
add("il pessimismo","pesimismus","Emoce a vlastnosti","A2","il pes-si-mis-mo","Il pessimismo blocca.","Pesimismus blokuje.");
add("la fiducia in sé","sebedůvěra","Emoce a vlastnosti","A2","la fi-du-cha in se","Ho fiducia in me stesso.","Věřím sám sobě.");
add("l'autostima","sebevědomí","Emoce a vlastnosti","A2","lau-to-sti-ma","Una buona autostima è importante.","Dobré sebevědomí je důležité.");
add("la resilienza","odolnost/houževnatost","Emoce a vlastnosti","B1","la re-zi-lj-en-dza","La resilienza aiuta a superare le difficoltà.","Houževnatost pomáhá překonávat obtíže.");
add("la spontaneità","bezprostřednost","Emoce a vlastnosti","A2","la spon-ta-ne-i-ta","La sua spontaneità è piacevole.","Jeho bezprostřednost je příjemná.");
add("la sincerità","upřímnost","Emoce a vlastnosti","A2","la sin-che-ri-ta","La sincerità è la base di un'amicizia.","Upřímnost je základem přátelství.");
add("il rispetto","úcta/respekt","Emoce a vlastnosti","A2","il ris-pet-to","Il rispetto reciproco.","Vzájemný respekt.");
add("la gentilezza","laskavost","Emoce a vlastnosti","A1","la dʒen-ti-let-tsa","Un gesto di gentilezza.","Laskavé gesto.");
add("la simpatia","sympatičnost","Emoce a vlastnosti","A1","la sim-pa-ti-a","Ha molta simpatia.","Je velmi sympatický.");
add("l'antipatia","nesympatičnost","Emoce a vlastnosti","A2","lan-ti-pa-ti-a","Provo antipatia.","Necítím k němu sympatie.");
add("la severità","přísnost","Emoce a vlastnosti","A2","la se-ve-ri-ta","La severità del giudice.","Přísnost soudce.");
add("la dolcezza","sladkost/jemnost","Emoce a vlastnosti","A2","la dol-chet-tsa","La dolcezza del suo sorriso.","Sladkost jejího úsměvu.");
add("la prudenza","opatrnost","Emoce a vlastnosti","A2","la pru-den-dza","Agisci con prudenza.","Jednej opatrně.");
add("l'audacia","smělost","Emoce a vlastnosti","A2","lau-da-cha","L'audacia di un esploratore.","Smělost průzkumníka.");
add("l'allegria","veselost","Emoce a vlastnosti","A1","lal-le-gri-a","La sua allegria è contagiosa.","Jeho veselost je nakažlivá.");
add("la malinconia","melancholie","Emoce a vlastnosti","A2","la ma-lin-ko-ni-a","Un senso di malinconia.","Pocit melancholie.");

// ═══════════════════════════════════════════════════════
// RODINA A VZTAHY (+59) — cíl: 100
// ═══════════════════════════════════════════════════════
add("il bisnonno","pradědeček","Rodina a vztahy","A2","il biz-non-no","Il mio bisnonno aveva 90 anni.","Můj pradědeček byl 90 let.");
add("la bisnonna","prababička","Rodina a vztahy","A2","la biz-non-na","La mia bisnonna cucina bene.","Moje prababička vaří dobře.");
add("il pronipote","pravnuk","Rodina a vztahy","A2","il pro-ni-po-te","Il mio primo pronipote.","Můj první pravnuk.");
add("la pronipote","pravnučka","Rodina a vztahy","A2","la pro-ni-po-te","La mia pronipote è piccola.","Moje pravnučka je malá.");
add("il gemello","dvojče (muž)","Rodina a vztahy","A1","il dʒe-mel-lo","Ho un fratello gemello.","Mám bratra dvojče.");
add("la gemella","dvojče (žena)","Rodina a vztahy","A1","la dʒe-mel-la","Ho una sorella gemella.","Mám sestru dvojče.");
add("il fratellastro","nevlastní bratr","Rodina a vztahy","A2","il fra-tel-las-tro","Il mio fratellastro vive a Roma.","Můj nevlastní bratr žije v Římě.");
add("la sorellastra","nevlastní sestra","Rodina a vztahy","A2","la so-rel-las-tra","La mia sorellastra è simpatica.","Moje nevlastní sestra je milá.");
add("il patrigno","nevlastní otec","Rodina a vztahy","A2","il pa-tri-njo","Il mio patrigno è gentile.","Můj nevlastní otec je laskavý.");
add("la matrigna","nevlastní matka","Rodina a vztahy","A2","la ma-tri-nja","La mia matrigna cucina bene.","Moje nevlastní matka vaří dobře.");
add("il padrino","kmotr","Rodina a vztahy","A2","il pa-dri-no","Il mio padrino al battesimo.","Můj kmotr při křtu.");
add("la madrina","kmotra","Rodina a vztahy","A2","la ma-dri-na","La mia madrina è amorevole.","Moje kmotra je laskavá.");
add("il figlioccio","kmotrěnec","Rodina a vztahy","A2","il fil-jot-cho","Il mio figlioccio si chiama Marco.","Můj kmotrěnec se jmenuje Marco.");
add("il pupillo","chráněnec","Rodina a vztahy","A2","il pu-pil-lo","È il pupillo del professore.","Je oblíbencem profesora.");
add("lo sposo","ženich/manžel","Rodina a vztahy","A1","lo spo-zo","Lo sposo è emozionato.","Ženich je dojatý.");
add("la sposa","nevěsta/manželka","Rodina a vztahy","A1","la spo-za","La sposa è bellissima.","Nevěsta je překrásná.");
add("il fidanzato","snoubenec","Rodina a vztahy","A1","il fi-dan-dza-to","Il mio fidanzato è gentile.","Můj snoubenec je laskavý.");
add("la fidanzata","snoubenka","Rodina a vztahy","A1","la fi-dan-dza-ta","La mia fidanzata è bella.","Moje snoubenka je krásná.");
add("il compagno","partner/druh","Rodina a vztahy","A1","il kom-pan-jo","Il mio compagno lavora qui.","Můj partner pracuje zde.");
add("la compagna","partnerka","Rodina a vztahy","A1","la kom-pan-ja","La mia compagna è brava.","Moje partnerka je šikovná.");
add("il vedovo","vdovec","Rodina a vztahy","A2","il ve-do-vo","È rimasto vedovo.","Zůstal vdovcem.");
add("la vedova","vdova","Rodina a vztahy","A2","la ve-do-va","La vedova di guerra.","Válečná vdova.");
add("il divorziato","rozvedený (muž)","Rodina a vztahy","A2","il di-vor-tsja-to","Un uomo divorziato.","Rozvedený muž.");
add("la divorziata","rozvedená (žena)","Rodina a vztahy","A2","la di-vor-tsja-ta","Una donna divorziata.","Rozvedená žena.");
add("il celibe","svobodný muž","Rodina a vztahy","A2","il che-li-be","È ancora celibe.","Stále je svobodný.");
add("la nubile","svobodná žena","Rodina a vztahy","A2","la nu-bi-le","È ancora nubile.","Stále je svobodná.");
add("adottato","adoptovaný","Rodina a vztahy","A2","a-dot-ta-to","Un bambino adottato.","Adoptované dítě.");
add("l'adozione","adopce","Rodina a vztahy","A2","la-do-tsjo-ne","L'adozione internazionale.","Mezinárodní adopce.");
add("il tutore","poručník","Rodina a vztahy","A2","il tu-to-re","Il tutore legale del bambino.","Zákonný poručník dítěte.");
add("la famiglia allargata","rozšířená rodina","Rodina a vztahy","A2","la fa-mil-ja al-lar-ga-ta","La famiglia allargata.","Rozšířená rodina.");
add("il matrimonio","manželství/svatba","Rodina a vztahy","A1","il ma-tri-mo-njo","Il matrimonio è sacro.","Manželství je posvátné.");
add("il divorzio","rozvod","Rodina a vztahy","A2","il di-vor-tsjo","Hanno chiesto il divorzio.","Požádali o rozvod.");
add("la separazione","separace","Rodina a vztahy","A2","la se-pa-ra-tsjo-ne","Una separazione consensuale.","Dobrovolná separace.");
add("la luna di miele","líbánky","Rodina a vztahy","A2","la lu-na di mje-le","La luna di miele alle Maldive.","Líbánky na Maledivách.");
add("il rapporto","vztah","Rodina a vztahy","A2","il rap-por-to","Un buon rapporto.","Dobrý vztah.");
add("il legame","pouto","Rodina a vztahy","A2","il le-ga-me","Un forte legame familiare.","Silné rodinné pouto.");
add("la cura","péče","Rodina a vztahy","A1","la ku-ra","La cura dei bambini.","Péče o děti.");
add("l'affetto","náklonnost","Rodina a vztahy","A2","laf-fet-to","Mostrare affetto.","Projevovat náklonnost.");
add("l'amore","láska","Rodina a vztahy","A1","la-mo-re","L'amore è bello.","Láska je krásná.");
add("l'amicizia","přátelství","Rodina a vztahy","A1","la-mi-chi-tsja","Un'amicizia sincera.","Upřímné přátelství.");
add("la lite","hádka","Rodina a vztahy","A2","la li-te","Una lite in famiglia.","Rodinná hádka.");
add("il litigio","spor","Rodina a vztahy","A2","il li-ti-dʒo","Un litigio tra fratelli.","Spor mezi sourozenci.");
add("la riconciliazione","smíření","Rodina a vztahy","A2","la ri-kon-chi-lja-tsjo-ne","La riconciliazione dopo la lite.","Smíření po hádce.");
add("il rispetto reciproco","vzájemný respekt","Rodina a vztahy","A2","il ris-pet-to re-chi-pro-ko","Il rispetto reciproco in famiglia.","Vzájemný respekt v rodině.");
add("la comprensione","pochopení","Rodina a vztahy","A2","la kom-pren-sjo-ne","La comprensione tra genitori e figli.","Pochopení mezi rodiči a dětmi.");
add("il sostegno","podpora","Rodina a vztahy","A2","il sos-ten-jo","Il sostegno familiare.","Rodinná podpora.");
add("crescere","vyrůstat","Rodina a vztahy","A1","kres-che-re","I bambini crescono velocemente.","Děti rychle rostou.");
add("educare","vychovávat","Rodina a vztahy","A2","e-du-ka-re","Educare bene i figli.","Dobře vychovávat děti.");
add("proteggere","chránit","Rodina a vztahy","A2","pro-tedʒ-dʒe-re","I genitori proteggono i figli.","Rodiče chrání děti.");
add("condividere la vita","sdílet život","Rodina a vztahy","A2","kon-di-vi-de-re la vi-ta","Condividiamo la vita insieme.","Sdílíme život spolu.");
add("stare insieme","být spolu","Rodina a vztahy","A1","sta-re in-sje-me","Stiamo bene insieme.","Jsme spolu dobře.");
add("la generazione","generace","Rodina a vztahy","A2","la dʒe-ne-ra-tsjo-ne","Le generazioni si incontrano.","Generace se setkávají.");
add("il cognome","příjmení","Rodina a vztahy","A1","il kon-jo-me","Qual è il tuo cognome?","Jaké je tvé příjmení?");
add("il nome di battesimo","křestní jméno","Rodina a vztahy","A2","il no-me di bat-te-zi-mo","Il mio nome di battesimo è Luca.","Mé křestní jméno je Luca.");
add("l'albero genealogico","rodokmen","Rodina a vztahy","A2","lal-be-ro dʒe-ne-a-lo-dʒi-ko","Il mio albero genealogico.","Můj rodokmen.");
add("l'erede","dědic","Rodina a vztahy","A2","le-re-de","L'erede della fortuna.","Dědic majetku.");
add("l'eredità","dědictví","Rodina a vztahy","A2","le-re-di-ta","L'eredità della famiglia.","Rodinné dědictví.");
add("il testamento","závěť","Rodina a vztahy","A2","il tes-ta-men-to","Ha lasciato un testamento.","Zanechal závěť.");
add("il lutto","smutek/truchlení","Rodina a vztahy","A2","il lut-to","È in lutto per la perdita.","Truchlí pro ztrátu.");
add("la perdita","ztráta","Rodina a vztahy","A2","la per-di-ta","La perdita di un caro.","Ztráta blízkého.");
add("il ricordo","vzpomínka","Rodina a vztahy","A2","il ri-kor-do","Un bel ricordo di famiglia.","Krásná rodinná vzpomínka.");

// ═══════════════════════════════════════════════════════
// PŘÍDAVNÁ JMÉNA (+57) — cíl: 100
// ═══════════════════════════════════════════════════════
add("veloce","rychlý","Přídavná jména","A1","ve-lo-che","Un'auto veloce.","Rychlé auto.");
add("lento","pomalý","Přídavná jména","A1","len-to","Un passo lento.","Pomalý krok.");
add("facile","snadný","Přídavná jména","A1","fa-chi-le","Un esercizio facile.","Snadné cvičení.");
add("difficile","těžký","Přídavná jména","A1","dif-fi-chi-le","Un problema difficile.","Těžký problém.");
add("lungo","dlouhý","Přídavná jména","A1","lun-go","Un percorso lungo.","Dlouhá trasa.");
add("corto","krátký","Přídavná jména","A1","kor-to","Un vestito corto.","Krátké šaty.");
add("alto","vysoký","Přídavná jména","A1","al-to","Un edificio alto.","Vysoká budova.");
add("basso","nízký","Přídavná jména","A1","bas-so","Un muretto basso.","Nízká zeď.");
add("largo","široký","Přídavná jména","A1","lar-go","Una strada larga.","Široká ulice.");
add("stretto","úzký","Přídavná jména","A1","stret-to","Un corridoio stretto.","Úzká chodba.");
add("pesante","těžký (váhou)","Přídavná jména","A1","pe-zan-te","Una valigia pesante.","Těžký kufr.");
add("leggero","lehký","Přídavná jména","A1","ledʒ-dʒe-ro","Un tessuto leggero.","Lehká látka.");
add("duro","tvrdý","Přídavná jména","A1","du-ro","Un materasso duro.","Tvrdá matrace.");
add("morbido","měkký","Přídavná jména","A1","mor-bi-do","Un cuscino morbido.","Měkký polštář.");
add("liscio","hladký","Přídavná jména","A2","li-sho","Una superficie liscia.","Hladký povrch.");
add("ruvido","drsný","Přídavná jména","A2","ru-vi-do","Un tessuto ruvido.","Drsná tkanina.");
add("piatto","rovný/plochý","Přídavná jména","A1","pjat-to","Un terreno piatto.","Rovný terén.");
add("curvo","zakřivený","Přídavná jména","A2","kur-vo","Una linea curva.","Zakřivená čára.");
add("rotondo","kulatý","Přídavná jména","A1","ro-ton-do","Un tavolo rotondo.","Kulatý stůl.");
add("quadrato","čtvercový","Přídavná jména","A1","kwa-dra-to","Un disegno quadrato.","Čtvercový výkres.");
add("triangolare","trojúhelníkový","Přídavná jména","A2","tri-an-go-la-re","Una forma triangolare.","Trojúhelníkový tvar.");
add("vuoto","prázdný","Přídavná jména","A1","vwo-to","Un bicchiere vuoto.","Prázdná sklenice.");
add("pieno","plný","Přídavná jména","A1","pje-no","Un piatto pieno.","Plný talíř.");
add("pulito","čistý","Přídavná jména","A1","pu-li-to","Un posto pulito.","Čisté místo.");
add("sporco","špinavý","Přídavná jména","A1","spor-ko","Le mani sporche.","Špinavé ruce.");
add("ordinato","uklizený","Přídavná jména","A2","or-di-na-to","Una stanza ordinata.","Uklizený pokoj.");
add("disordinato","nepořádný","Přídavná jména","A2","dis-or-di-na-to","Un ufficio disordinato.","Nepořádná kancelář.");
add("utile","užitečný","Přídavná jména","A1","u-ti-le","Un consiglio utile.","Užitečná rada.");
add("inutile","zbytečný","Přídavná jména","A2","i-nu-ti-le","Un oggetto inutile.","Zbytečný předmět.");
add("necessario","nutný","Přídavná jména","A2","ne-ches-sa-rjo","È necessario studiare.","Je nutné studovat.");
add("impossibile","nemožný","Přídavná jména","A2","im-pos-si-bi-le","È impossibile!","To je nemožné!");
add("possibile","možný","Přídavná jména","A1","pos-si-bi-le","È possibile?","Je to možné?");
add("probabile","pravděpodobný","Přídavná jména","A2","pro-ba-bi-le","È probabile che piova.","Pravděpodobně bude pršet.");
add("sicuro","jistý/bezpečný","Přídavná jména","A1","si-ku-ro","Un posto sicuro.","Bezpečné místo.");
add("pericoloso","nebezpečný","Přídavná jména","A1","pe-ri-ko-lo-zo","Una situazione pericolosa.","Nebezpečná situace.");
add("adatto","vhodný","Přídavná jména","A2","a-dat-to","Un film adatto ai bambini.","Film vhodný pro děti.");
add("inadatto","nevhodný","Přídavná jména","A2","in-a-dat-to","Un comportamento inadatto.","Nevhodné chování.");
add("vero","pravdivý/skutečný","Přídavná jména","A1","ve-ro","Una storia vera.","Pravdivý příběh.");
add("falso","nepravdivý/falešný","Přídavná jména","A1","fal-so","Una notizia falsa.","Falešná zpráva.");
add("strano","divný","Přídavná jména","A1","stra-no","Che situazione strana!","Jaká divná situace!");
add("normale","normální","Přídavná jména","A1","nor-ma-le","È normale.","Je to normální.");
add("particolare","zvláštní/specifický","Přídavná jména","A2","par-ti-ko-la-re","Un caso particolare.","Zvláštní případ.");
add("comune","běžný/společný","Přídavná jména","A2","ko-mu-ne","Un problema comune.","Běžný problém.");
add("unico","jedinečný","Přídavná jména","A2","u-ni-ko","Un'esperienza unica.","Jedinečný zážitek.");
add("originale","originální","Přídavná jména","A2","o-ri-dʒi-na-le","Un'idea originale.","Originální nápad.");
add("moderno","moderní","Přídavná jména","A1","mo-der-no","Un design moderno.","Moderní design.");
add("antico","starý/antický","Přídavná jména","A1","an-ti-ko","Un palazzo antico.","Starý palác.");
add("attuale","aktuální","Přídavná jména","A2","at-twa-le","La situazione attuale.","Aktuální situace.");
add("recente","nedávný","Přídavná jména","A2","re-chen-te","Un evento recente.","Nedávná událost.");
add("futuro","budoucí","Přídavná jména","A2","fu-tu-ro","Un progetto futuro.","Budoucí projekt.");
add("passato","minulý","Přídavná jména","A2","pas-sa-to","Un evento passato.","Minulá událost.");
add("forte","silný","Přídavná jména","A1","for-te","Un vento forte.","Silný vítr.");
add("debole","slabý","Přídavná jména","A1","de-bo-le","Sento debole.","Cítím se slabý.");
add("ricco","bohatý","Přídavná jména","A1","rik-ko","Un uomo ricco.","Bohatý muž.");
add("povero","chudý","Přídavná jména","A1","po-ve-ro","Un quartiere povero.","Chudá čtvrť.");
add("felice","šťastný","Přídavná jména","A1","fe-li-che","Sono felice oggi.","Dnes jsem šťastný.");
add("infelice","nešťastný","Přídavná jména","A1","in-fe-li-che","Si sente infelice.","Cítí se nešťastný.");
add("sano","zdravý","Přídavná jména","A1","sa-no","Uno stile di vita sano.","Zdravý životní styl.");
add("malato","nemocný","Přídavná jména","A1","ma-la-to","Sono malato oggi.","Dnes jsem nemocný.");

// Výpis do souboru
const fs = require('fs');
const outPath = `${__dirname}/massive_words_4.json`;
fs.writeFileSync(outPath, JSON.stringify(words, null, 2), 'utf8');

const counts = {};
words.forEach(w => { counts[w.category] = (counts[w.category] || 0) + 1; });
console.log('\n=== PŘIDÁNO SLOV PER KATEGORIE ===');
Object.entries(counts).sort((a,b) => b[1]-a[1]).forEach(([cat, cnt]) => {
  console.log(`  ${cat}: ${cnt}`);
});
console.log(`\nCELKEM: ${words.length} nových slov\n`);
